### ISSUE TITLE
Weird `type annotations needed` error caused by irrelevant code

### ISSUE THREAD

**Issue by mss1451** [rust-lang/rust#100084]
I tried this code:

```rust
fn main() {
    // Delete the following line to get rid of the error
    let a: String = serde_yaml::from_str("").unwrap();

    if 1_u16 == 2_u8 as _ { // Error: type annotations needed (E0282)
        println!("???");
    }
}
```
```toml
[package]
name = "bug_test"
authors = ["x"]
version = "0.1.0"
edition = "2021"

[dependencies]
# At least using version 0.9.2 eliminates the error
serde_yaml = "0.8.26"
```

I expected to see this happen: Compiled successfully

Instead, this happened:
```
error[E0282]: type annotations needed
 --> src/main.rs:5:25
  |
5 |     if 1_u16 == 2_u8 as _ { // Error: type annotations needed (E0282)
  |                         ^ cannot infer type
```
Deleting the first line of the code eliminates the error but I can't see how they are related. I suspect that this is a compiler bug.
### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (fe3342816 2022-08-01)
binary: rustc
commit-hash: fe3342816a282949f014caa05ea2e669ff9d3d3c
commit-date: 2022-08-01
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```
Also tried the stable version:
```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-unknown-linux-gnu
release: 1.62.1
LLVM version: 14.0.5
```
