### ISSUE TITLE
Invalid instruction when using MCR instruction in inline assembly (ARMv8m)

### ISSUE THREAD

**Issue by spcan** [rust-lang/rust#101458]
I tried this code:

```rust
pub fn main() {
    let value = 0.0f32;
    unsafe { core::arch::asm!("mcr p0, #0, {x}, 0, 0, #0", x = in(reg) value, options(nomem, nostack)) }
}
```

config.toml file:
```toml
[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",

    # Code optimizations
    #"-Z", "trap-unreachable=no",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[build]
target = "thumbv8m.main-none-eabihf"
```
I expected to see this happen:

Correct compilation of the MCR instruction. This instruction is a valid ARMv8m instruction available in thumb mode. It moves a register's value and some operands into a coprocessor.

Instead, this happened:

```shell
error: invalid instruction
  |
note: instantiated into assembly here
 --> <inline asm>:1:2
  |
1 |     mcr p0, #0, r0, 0, 0, #0
  |     ^
```

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (02654a084 2022-08-30)
binary: rustc
commit-hash: 02654a0844f5c8d29bac318c3c6c666da3d8543d
commit-date: 2022-08-30
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
error: invalid instruction
  |
note: instantiated into assembly here
 --> <inline asm>:1:2
  |
1 |     mcr p0, #0, r0, 0, 0, #0
  |     ^
```

</p>
</details>
