### ISSUE TITLE
Rustdoc: Test fails on "unresolved import" though test doesn't use any crate

### ISSUE THREAD

**Issue by mirao** [rust-lang/rust#103775]
I tried this code (`src/main.rs`):

```rust
use regex::Regex;

/// ```
/// assert!(true)
/// ```
fn main() {
    println!("Hello, world!");
    let regex = Regex::new("^Hello").unwrap();
    println!("{}", regex);
}
```
with `Cargo.toml`
```toml
[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
```
I run `rustdoc --test src/main.rs`

I expected to see this happen:
```
running 1 test
test src/main.rs - main (line 1) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.20s
```

Instead, this happened:
```
error[E0432]: unresolved import `regex`
 --> src/main.rs:1:5
  |
1 | use regex::Regex;
  |     ^^^^^ maybe a missing crate `regex`?
  |
  = help: consider adding `extern crate regex` to use the `regex` crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
```
Note that `cargo run` works well
```
$ cargo run
   Compiling hello_world v0.1.0 (/home/mirao/workspace/rust/hello_world)
    Finished dev [unoptimized + debuginfo] target(s) in 1.34s
     Running `target/debug/hello_world`
Hello, world!
^Hello
```
### Meta

`rustc --version --verbose`:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```
`rustdoc --version`
```
rustdoc 1.64.0 (a55dd71d5 2022-09-19)
```
I'm running Ubuntu 22.04
