### ISSUE TITLE
Wrong architecture objects mixed in self-built compiler

### ISSUE THREAD

**Issue by mkroening** [rust-lang/rust#105065]
When using a self-built compiler on an Apple Silicon host to build a `x86_64-unknown-none` static library, `mach-o-arm64` objects get mixed into the output. This happens since https://github.com/rust-lang/rust/pull/103732.

# Problem setup

```toml
# config.toml
# using stage1, built with `./x.py build`
changelog-seen = 2

[llvm]
targets = "AArch64;RISCV;X86"

[build]
target = [
    "aarch64-apple-darwin",
    "x86_64-unknown-none",
    "x86_64-unknown-hermit",
    "aarch64-unknown-hermit",
]

[rust]
deny-warnings = false
llvm-tools = true
lld = true
```

```
host: aarch64-apple-darwin
```

```rust
// foo.rs
#![no_std]

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
```

```
$ rustc --crate-type staticlib --target x86_64-unknown-none foo.rs
$ objdump --archive-headers libfoo.a
```

# Results

1. 33b530e04099465a8029ef581202d52f4075558e
    * [33b530e.log](https://github.com/rust-lang/rust/files/10116319/33b530e.log)
    * does not contain any `mach-o-arm64` files
2. 5984b1d86f0e7221c83c0d63b8d63fc0de9c5760 (the next commit)
    * [5984b1d.log](https://github.com/rust-lang/rust/files/10116320/5984b1d.log)
    * contains `absvdi2.o: file format mach-o-arm64` and more
3. `nightly-2022-11-01` (the next nightly)
    * [nightly-2022-11-01.log](https://github.com/rust-lang/rust/files/10116427/nightly-2022-11-01.log)
    * does not contain any `mach-o-arm64` files

CC: @stlankes

**Comment by mkroening** [comment]
This was broken before 3acb505ee560770c62bad5362f6caf7567d467b9 as well, I wonder why we did not notice in the past. 🤔

**Comment by mkroening** [comment]
CC: @jyn514

**Comment by jyn514** [comment]
I don't understand why this only broke now, but I'm glad https://github.com/rust-lang/rust/pull/102579 fixes it.

You probably weren't checking out the `llvm-project` submodules and just recently started doing that.

**Comment by mkroening** [comment]
Well, thinking about it, I got my machine quite recently, so I might just have never tried with this setup before. 😅 

I always had the `llvm-project` submodule checked out, though.

**Comment by Jamesbarford** [comment]
Triage; if this is no longer and issue may we close?

cc @davidtwco

**Comment by mkroening** [comment]
Thanks for your patience!

I have tested this again and got the following results:

```toml
# config.toml
change-id = 118724

[llvm]
download-ci-llvm = false
targets = "AArch64;X86"

[build]
target = [
    "aarch64-apple-darwin",
    "x86_64-unknown-none",
]
optimized-compiler-builtins = true

[rust]
llvm-tools = true
lld = true
```

- 735f7589e3d7d28c2e1bc5c241750ee069d0d65a contains mach-o-arm64 files.
- 9c3ad802d9b9633d60d3a74668eb1be819212d34 does not contain any mach-o-arm64 files.
- e29fcf45e4ae686d77b490bf07320f0d3a2cf35f (nightly-2026-01-05) does not contain any mach-o-arm64 files.

I confirmed that this was fixed by upgrading cc-rs from 1.0.79 to 1.0.85. I did not pinpoint which one exactly because of https://github.com/rust-lang/cc-rs/issues/913, but in between these versions, there were several Apple-related fixes. Thus, I will close this issue, hoping the root cause has been resolved.

@jyn514, if you suspect there may be more to this issue, feel free to reopen! :)
