### ISSUE TITLE
cannot bootstrap with debug assertions: `LLVM ERROR: Function Import: link error: linking module flags 'PIC Level': IDs have conflicting behaviors in 'psm-e65bd90221787d18.psm.6652f06d-cgu.0.rcgu.o' and 'rustc_mir_build-88c96d56ce04b16a.rustc_mir_build.dfcbe143-cgu.6.rcgu.o'`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#109382]
I am trying to bootstrap with
````toml
changelog-seen = 2
[llvm]
download-ci-llvm = false
thin-lto = true
assertions = true
ccache = "/home/matthias/.cargo/bin/sccache"
ninja = true
targets = "X86"
link-jobs = 2
cflags = "-march=native" # -D_GLIBCXX_DEBUG
cxxflags = "-march=native" # -D_GLIBCXX_DEBUG
ldflags = "-march=native" # -D_GLIBCXX_DEBUG
polly = true
[build]
dist-stage = 2
install-stage = 2
extended = true
tools = ["cargo", "clippy", "rustfmt", "analysis", "src", "miri"] # + "rust-demangler" if `profiler`
low-priority = true
[install]
prefix = "/home/matthias/.rustup/toolchains/local-debug-assertions"
sysconfdir = "etc"
[rust]
debug = true
debug-assertions = true
debug-assertions-std = true
overflow-checks = true
overflow-checks-std = true
debuginfo-level = 1
codegen-backends = ["llvm", "cranelift"]
backtrace-on-ice = true
verify-llvm-ir = true
lto = "thin"
[target.x86_64-unknown-linux-gnu]
[dist]
compression-formats = ["xz"]
````

and x.py install fails with 

````
   Compiling rustc_driver v0.0.0 (/home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver)
LLVM ERROR: Function Import: link error: linking module flags 'PIC Level': IDs have conflicting behaviors in 'psm-e65bd90221787d18.psm.6652f06d-cgu.0.rcgu.o' and 'rustc_mir_build-88c96d56ce04b16a.rustc_mir_build.dfcbe143-cgu.6.rcgu.o'
error: could not compile `rustc_driver`

````
@  9d0eac4d02da8a1b139ff3dca7fc4b458fb99eb6
