### ISSUE TITLE
`./configure` doesn't support lists

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#109316]
I tried this code:

```rust
../configure --set rust.codegen-backends=[rustc_codegen_cranelift]
```

I expected to see this happen: configure generates
```toml
[rust]
codegen-backends = ["rustc_codegen_cranelift"]
```

Instead, this happened: configure generates
```toml
[rust]
codegen-backends = '[rustc_codegen_cranelift]'
```
which fails to parse.

### Meta

HEAD is branched from https://github.com/rust-lang/rust/commit/13afbdaa0655dda23d7129e59ac48f1ec88b2084
