### ISSUE TITLE
rustc panics with &'static [u8] and ouroboros self_referencing

### ISSUE THREAD

**Issue by muja** [rust-lang/rust#113997]
While trying to check my code with miri, I had to replace occurrences of `std::fs::File` with `&'static [u8]` (and use `include_bytes!`).

The following code triggers a rustc panic. The same code with `std::fs::File` compiles fine.

```rust
use ouroboros::self_referencing;
use rc_zip::reader::sync::{EntryReader, HasCursor, SyncArchive};

#[self_referencing]
pub struct Docx {
    file: &'static [u8],
    #[borrows(file)]
    #[covariant]
    arc: SyncArchive<'this, &'static [u8]>,
    #[borrows(arc)]
    #[covariant]
    readers: Vec<xml::EventReader<EntryReader<<&'static [u8] as HasCursor>::Cursor<'this>>>>,
}

fn main(){}
```

stderr/stdout combined (was too long for GitHub, so attaching):

[output.txt](https://github.com/rust-lang/rust/files/12141909/output.txt)

The same error occurs with stable: `note: rustc 1.71.0 (8ede3aae2 2023-07-12) running on x86_64-apple-darwin`

Cargo.toml:

```toml
[package]
name = "ziptest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ouroboros = "0.17.2"
rc-zip = "2.0.1"

xml-rs = "0.8.16"
```

[Cargo.lock](https://github.com/rust-lang/rust/files/12141888/Cargo.lock.txt) is attached.
