### ISSUE TITLE
Source installation tries to install LLVM sources even if system LLVM used

### ISSUE THREAD

**Issue by o01eg** [rust-lang/rust#114940]
I'm trying to install rust with system LLVM and without `src/llvm-project` folder. It builds successfully but installation fails when trying to copy missing `src/llvm-project/libunwind`.

```
Copy "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/library/alloc/benches/btree/map.rs" to "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/tmp/tarball/rust-src/image/lib/rustlib/src/rust/library/alloc/benches/btree/map.rs"
Copy "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/library/alloc/benches/binary_heap.rs" to "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/tmp/tarball/rust-src/image/lib/rustlib/src/rust/library/alloc/benches/binary_heap.rs"
Copy "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/library/alloc/Cargo.toml" to "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/tmp/tarball/rust-src/image/lib/rustlib/src/rust/library/alloc/Cargo.toml"
thread 'main' panicked at 'could not read dir "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/llvm-project/libunwind": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1714:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7ba605cd90d6467bda469d1cd2148ac32ea562bf/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/7ba605cd90d6467bda469d1cd2148ac32ea562bf/library/core/src/panicking.rs:67:14
   2: bootstrap::Build::read_dir
             at ./src/bootstrap/lib.rs:1714:25
   3: bootstrap::Build::recurse_
             at ./src/bootstrap/lib.rs:1650:18
   4: bootstrap::Build::cp_filtered
             at ./src/bootstrap/lib.rs:1645:9
   5: bootstrap::dist::copy_src_dirs
             at ./src/bootstrap/dist.rs:880:9
   6: <bootstrap::dist::Src as bootstrap::builder::Step>::run
             at ./src/bootstrap/dist.rs:921:9
   7: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:2087:23
   8: <bootstrap::install::Src as bootstrap::builder::Step>::run
             at ./src/bootstrap/install.rs:278:23
   9: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:2087:23
  10: <bootstrap::install::Src as bootstrap::builder::Step>::make_run
             at ./src/bootstrap/install.rs:274:9
  11: bootstrap::builder::StepDescription::maybe_run
             at ./src/bootstrap/builder.rs:315:13
  12: bootstrap::builder::StepDescription::run
             at ./src/bootstrap/builder.rs:354:21
  13: bootstrap::builder::Builder::run_step_descriptions
             at ./src/bootstrap/builder.rs:959:9
  14: bootstrap::builder::Builder::execute_cli
             at ./src/bootstrap/builder.rs:940:9
  15: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:704:13
  16: bootstrap::main
             at ./src/bootstrap/bin/main.rs:74:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/7ba605cd90d6467bda469d1cd2148ac32ea562bf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/./x.py", line 50, in <module>
    bootstrap.main()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 1111, in main
    bootstrap(args)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 1086, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 184, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/bootstrap install -vv --config=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/config.toml -j6
```

config.toml:
```toml
changelog-seen = 2
[llvm]
download-ci-llvm = false
optimize = true
release-debuginfo = false
assertions = false
ninja = true
targets = "X86;Mips;NVPTX;RISCV;BPF;AArch64;WebAssembly"
experimental-targets = ""
link-shared = true


enable-warnings = false
[llvm.build-config]
CMAKE_VERBOSE_MAKEFILE = "ON"
CMAKE_C_FLAGS_RELEASE = "-O2 -march=native -pipe -fomit-frame-pointer"
CMAKE_CXX_FLAGS_RELEASE = "-O2 -march=native -pipe -fomit-frame-pointer"
CMAKE_EXE_LINKER_FLAGS_RELEASE = "-O1"
CMAKE_MODULE_LINKER_FLAGS_RELEASE = "-O1"
CMAKE_SHARED_LINKER_FLAGS_RELEASE = "-O1"
CMAKE_STATIC_LINKER_FLAGS_RELEASE = ""
[build]
build-stage = 2
test-stage = 2
doc-stage = 2
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["i686-unknown-linux-gnu","x86_64-unknown-linux-gnu","wasm32-unknown-unknown"]
docs = true
compiler-docs = true
submodules = false
python = "python3.11"
locked-deps = true
vendor = false
extended = true
tools = ["cargo","rustdoc","clippy","rustfmt","rust-analyzer","analysis","src"]
verbose = 2
sanitizers = false
profiler = false
cargo-native-static = false
[install]
prefix = "/usr/lib/rust/9999"
sysconfdir = "etc"
docdir = "share/doc/rust"
bindir = "bin"
libdir = "lib"
mandir = "share/man"
[rust]
# https://github.com/rust-lang/rust/issues/54872
codegen-units-std = 1
optimize = true
debug = false
debug-assertions = false
debug-assertions-std = false
debuginfo-level = 0
debuginfo-level-rustc = 0
debuginfo-level-std = 0
debuginfo-level-tools = 0
debuginfo-level-tests = 0
backtrace = true
incremental = false
default-linker = "x86_64-pc-linux-gnu-gcc"
parallel-compiler = false
description = "gentoo"
rpath = false
verbose-tests = true
optimize-tests = true
codegen-tests = true
dist-src = false
remap-debuginfo = true
lld = false
# only deny warnings if doc+wasm are NOT requested, documenting stage0 wasm std fails without it
# https://github.com/rust-lang/rust/issues/74976
# https://github.com/rust-lang/rust/issues/76526
deny-warnings = false
backtrace-on-ice = true
jemalloc = false
lto = "fat"
[dist]
src-tarball = false
compression-formats = ["xz"]
compression-profile = "balanced"
[target.i686-unknown-linux-gnu]
ar = "x86_64-pc-linux-gnu-ar"
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ranlib = "x86_64-pc-linux-gnu-ranlib"
llvm-libunwind = "no"
llvm-config = "/usr/lib/llvm/16/bin/llvm-config"
[target.x86_64-unknown-linux-gnu]
ar = "x86_64-pc-linux-gnu-ar"
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ranlib = "x86_64-pc-linux-gnu-ranlib"
llvm-libunwind = "no"
llvm-config = "/usr/lib/llvm/16/bin/llvm-config"
[target.wasm32-unknown-unknown]
linker = "lld"
# wasm target does not have profiler_builtins https://bugs.gentoo.org/848483
profiler = false
```

OS: Gentoo Linux AMD64
Rustc version: https://github.com/rust-lang/rust/commit/4a0402cd805aa1f4dd8e2d96b038be664db293c3
