### ISSUE TITLE
Rust fails to build cross target libraries when building on M1 Mac

### ISSUE THREAD

**Issue by athei** [rust-lang/rust#115679]
I am trying to build Rust from source. Besides my host target `aarch64-apple-darwin` I also want to build support for another target. Let's say `x86_64-apple-darwin` (it doesn't really matter as it happens for all targets as far as I can tell).

When I do this it will always emit the following warning and just skip building those targets support (only host support is present then).

```
Building stage2 library artifacts (aarch64-apple-darwin -> x86_64-apple-darwin)
...
    Finished release [optimized] target(s) in 16.01s
Warning: no codegen-backends config matched the requested path to build a codegen backend. Help: add backend to codegen-backends in config.toml.
```

## My System

Mac Studio 2022
macOS: 13.5.2 (22G91)

## How to reproduce

This is my config. Apart from that I just checked out Rust and ran the build command:

```toml
profile = 'dist'
changelog-seen = 2

[llvm]

[build]

configure-args = []

target = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
]

[install]

[rust]

[dist]

```

```sh
git clone https://github.com/rust-lang/rust.git
# latest commit i can reproduce this for
git checkout 309af3442a1808888e3ceb2eacccbf4140eba1e0
git submodule update --recursive
cd rust
./x build
```
