### ISSUE TITLE
Combining LTO + PGO + lib/cdylib crashes on LLVM assertion

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rust#117220]
When compiling a cargo project with:
- LTO enabled (`LTO=thin/fat`)
- PGO (`-Cprofile-use`)
- Both `lib` and `dylib` targets for its library

Reproducer
```rust
// src/main.rs
use clap::Command;

fn main() {
    Command::new("a").about("a");
}
```

```toml
# Cargo.toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.24" , default-features = false, features = ["std"]}

[profile.release]
lto = "thin"

[lib]
crate-type = ["lib", "cdylib"]
```

There also needs to be an empty `src/lib.rs` file. Here is a reproducer script for PGO:
```bash
#!/bin/bash

set -e

VERSION=${1:-1.71}

rustup install ${VERSION}
rustup component add llvm-tools-preview --toolchain ${VERSION}
rm -rf target
rm -rf /tmp/pgo
RUSTFLAGS="-Cprofile-generate=/tmp/pgo" cargo +${VERSION} build --release
./target/release/hello /tmp
`rustc +${VERSION} --print=sysroot`/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata merge -o merged-${VERSION}.profdata /tmp/pgo/*
RUSTFLAGS="-Cprofile-use=${PWD}/merged-${VERSION}.profdata" cargo +${VERSION} build --release
```

I expected to see this happen: the project compiles.

Instead, compilation fails with the following error:
```
module flag identifiers must be unique (or of 'require' type)
!"CG Profile"
LLVM ERROR: Broken module found, compilation aborted!
```

This was originally found in https://github.com/rust-lang/rust/issues/115344, which contains many examples of this problem in the wild. Here I sent a minimal example, I wasn't able to minimize it further (removing LTO, PGO, clap or lib/dylib) fixes the problem.

### Meta
`rustc --version --verbose`:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```
I managed to reproduce this all the way back to `1.60.0` (although this specific example requires at least `1.70.0` due to `clap`).

**Comment by DianQK** [comment]
I can reproduce the issue either with the `Cargo.toml` or using the lock file below.

```toml
# Cargo.toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.3.24" , default-features = false, features = ["std"]}

[profile.release]
lto = "thin"

[lib]
crate-type = ["lib", "cdylib"]
```

<details><summary>Cargo.lock</summary>
<p>

```toml
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anstyle"
version = "1.0.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "038dfcf04a5feb68e9c60b21c9625a54c2c0616e79b72b0fd87075a056ae1d1b"

[[package]]
name = "clap"
version = "4.3.24"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "fb690e81c7840c0d7aade59f242ea3b41b9bc27bcd5997890e7702ae4b32e487"
dependencies = [
 "clap_builder",
]

[[package]]
name = "clap_builder"
version = "4.3.24"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5ed2e96bc16d8d740f6f48d663eddf4b8a0983e79210fd55479b7bcd0a69860e"
dependencies = [
 "anstyle",
 "clap_lex",
]

[[package]]
name = "clap_lex"
version = "0.5.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cd7cc57abe963c6d3b9d8be5b06ba7c8957a930305ca90304f24ef040aa6f961"

[[package]]
name = "hello"
version = "0.1.0"
dependencies = [
 "clap",
]
```

</p>
</details>

**Comment by DianQK** [comment]
## Minimal Reproduction

First, let me provide a minimal reproduction:

```toml
# Cargo.toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"  # "thin" is also ok.

[lib]
crate-type = ["lib", "cdylib"]
```

```rust
// src/lib.rs
pub fn foo() {
    let mut v = Vec::new();
    v.push(1);
}
```

```rust
// src/main.rs
fn main() {
    hello::foo();
}
```

Next, run the PGO script similar to the one described in the issue.

## Why

### What LLVM Did

The LLVM error indicates that we created two `!"CG Profile"`.

This happens because every time we effectively run `cg-profile`, it creates a flag:
https://github.com/llvm/llvm-project/blob/602634d70cba2c51f6177740c4a98a377d10ab6a/llvm/lib/Transforms/Instrumentation/CGProfile.cpp#L42-L44

A simple example: https://llvm.godbolt.org/z/5bzeh6e77.

For me, running it multiple times might lead to unexpected behavior, and I'm not sure if the data can be merged or ignored here. cc @nikic

### What rustc/cargo Did

The key point now is understanding why we are running `CGProfile` twice. The key parameters for the commands executed by cargo are as follows:

```bash
rustc src/lib.rs --crate-type lib --crate-type cdylib -Cprofile-use=merged.profdata
rustc src/main.rs --crate-type bin -C lto=fat --extern hello=/path/libhello.rlib -Cprofile-use=merged.profdata
```

> We can remove `--crate-type cdylib`.

Because we did not pass `-Clinker-plugin-lto`, PGO data was applied when building `libhello.rlib`.
Finally, when building the `bin`, LTO added `libhello.rlib` that has the `"CG Profile"` flag.

## How to Fix

I believe the key is that `crate-type = ["lib", "cdylib"]` is causing `cargo` to omit the `-Clinker-plugin-lto` and `-Clto=fat`.

> Yes, there's also the issue that `cdylib` doesn't apply `-Clto=fat`.

Perhaps we should split this into two separate `rustc` commands? Or find a way to correctly pass these two parameters to different `crate-type`? cc @weihanglo

## Discovery Process

> Some may be interested in this.

A brief description:

1. Use `-Csave-temps` to get the LTO input IR and reproduce the issue using `opt -O2`.
2. (At this point, I wasn't yet aware of `CGProfile`) Use `llvm-reduce` to minimize this IR, and read the `CGProfile` code. I believe we executed this pass multiple times.
3. Use `-Csave-temps` and `llvm-dis` to find that the `clap_builder` IR includes the `!"CG Profile"`.
4. I tried removing some code in `clap_builder` to reproduce the issue and realized that PGO only handles runtime path. I guessed this was the key, so I remained the calling code, and finally arrived at a minimal reproduction.
