### ISSUE TITLE
Compile ohos target fail

### ISSUE THREAD

**Issue by Sword-Destiny** [rust-lang/rust#117780]
When build ohos-toolchain with ./x.py dist

get error:
thread 'main' panicked at src/lib.rs:1731:25:
could not read dir "/home/xxx/code/rust/build/aarch64-unknown-linux-ohos/compiler-doc": 0s {code:2, kind:NotFound, message:"No such file or directory"}

config.toml
```toml
profile = "compiler"
change-id = 116881

[build]
sanitizers = true
profiler = true
extended = true
tools = ["cargo", "rls", "clippy", "analysis", "src", "rustfmt"]
target = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-ohos", "x86_64-unknown-linux-ohos"]

[target.aarch64-unknown-linux-ohos]
cc = "/opt/aarch64-unknown-linux-ohos-clang.sh"
cxx = "/opt/aarch64-unknown-linux-ohos-clang++.sh"
ar = "/opt/ohos-sdk/linux/native/llvm/bin/llvm-ar"
ranlib = "/opt/ohos-sdk/linux/native/llvm/bin/llvm-ranlib"
linker  = "/opt/aarch64-unknown-linux-ohos-clang.sh"

[target.x86_64-unknown-linux-ohos]
cc = "/opt/x86_64-unknown-linux-ohos-clang.sh"
cxx = "/opt/x86_64-unknown-linux-ohos-clang++.sh"
ar = "/opt/ohos-sdk/linux/native/llvm/bin/llvm-ar"
ranlib = "/opt/ohos-sdk/linux/native/llvm/bin/llvm-ranlib"
linker  = "/opt/x86_64-unknown-linux-ohos-clang.sh"

```

@Amanieu
