### ISSUE TITLE
ICE: Expected type for ... but found Lifetime(ReErased) when substituting

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#119064]
https://github.com/oxidecomputer/cancel-safe-futures on commit `857ddd3a30c5f82e6edb72ac7c8a471860501d9f`

```
RUSTFLAGS="-Zinline-mir -Zcross-crate-inline-threshold=always -Zinline-mir-hint-threshold=10000 -Zinline-mir-threshold=10000" cargo +nightly test --target=x86_64-unknown-linux-gnu
```
If you don't set a `--target` you will OOM while optimizing syn with these very silly flags.

```
error: internal compiler error: compiler/rustc_middle/src/ty/generic_args.rs:885:9: expected type for `T/#0` (T/#0/0) but found Lifetime(ReErased) when substituting
```
```
error: internal compiler error: compiler/rustc_middle/src/ty/generic_args.rs:885:9: expected type for `T/#0` (T/#0/0) but found Lifetime(ReErased) when substituting
```

I also have another example of this that produces a "but found Const` ICE. They look similar, I'll post the other one later if someone wants.

[rustc-ice-2023-12-18T05_32_24-344139.txt](https://github.com/rust-lang/rust/files/13699738/rustc-ice-2023-12-18T05_32_24-344139.txt)

**Comment by saethlin** [comment]
I've been able to minimize to this:
```toml
[package]
name = "cancel-safe-futures"
edition = "2021"

[dependencies]
futures-core = { version = "0.3.28" }
futures-util = { version = "0.3.28" }
tokio = { version = "1.28.2", features = ["macros", "sync"] }
futures-lite = "2.1.0"
```
```rust
use futures_core::future::BoxFuture;
use futures_util::FutureExt;
use tokio::sync::MutexGuard;
use futures_lite::future::block_on;

async fn run() {
    let m = tokio::sync::Mutex::new(());
    let _ = async move {
        let permit = ActionPermit { guard: m.lock().await };
        cancel_perform_async_boxed(permit).await;
    }
    .await;
}

fn main() {
    block_on(run())
}

async fn cancel_perform_async_boxed<T>(permit: ActionPermit<'_, T>) {
    let fut = permit.perform_async_boxed(|_| async move {}.boxed());
    tokio::select! {
        _ = fut => {}
    }
}

struct ActionPermit<'a, T> {
    guard: MutexGuard<'a, T>,
}

impl<'a, T> ActionPermit<'a, T> {
    async fn perform_async_boxed<R, F>(mut self, action: F) -> R
    where
        F: for<'lock> FnOnce(&'lock mut T) -> BoxFuture<'lock, R>,
    {
        action(&mut *self.guard).await
    }
}
```
