### ISSUE TITLE
x.py install clones llvm although its never needed

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#121316]
````
Building tool miri (stage2 -> stage3, x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.14s
Building tool cargo-miri (stage2 -> stage3, x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.13s
Dist miri-1.78.0-dev-x86_64-unknown-linux-gnu
	finished in 0.473 seconds
Installing stage2 miri (x86_64-unknown-linux-gnu)
install: uninstalling component 'miri-preview'
install: creating uninstall script at /home/gh-matthiaskrgr/.rustup/toolchains/master/lib/rustlib/uninstall.sh
install: installing component 'miri-preview'

    miri installed.

Updating submodule src/llvm-project
* clones submodule *
Submodule path 'src/llvm-project': checked out '9ea7f739f257b049a65deeb1f2455bb2ea021cfa'
Dist rust-src-1.78.0-dev
	finished in 0.969 seconds
Installing stage2 src

````

This was interesting since x.py install never built llvm until it needed it during install (?) but  only the sources (??) although I had `download-ci-llvm=true`

```toml
changelog-seen = 2
[llvm]
download-ci-llvm = true
assertions = false
ninja = true
link-jobs = 16
[build]
dist-stage = 2
install-stage = 2
extended = true
tools = ["cargo", "clippy", "rustfmt", "analysis", "src", "miri"] # + "rust-demangler" if `profiler`
low-priority = true
[install]
prefix = "/home/gh-matthiaskrgr/.rustup/toolchains/master"
sysconfdir = "etc"
[rust]
debug = true
debug-assertions = false
debug-assertions-std = false
overflow-checks = false
overflow-checks-std = false
debuginfo-level = 1
codegen-backends = ["llvm", "cranelift"]
backtrace-on-ice = true
verify-llvm-ir = true
lto = "thin"
[target.x86_64-unknown-linux-gnu]
[dist]
compression-formats = ["xz"]
```
