### ISSUE TITLE
Regression: Cannot build the compiler for aarch64-apple-tvos-sim using Rust 1.78.0

### ISSUE THREAD

**Issue by Kentzo** [rust-lang/rust#124825]
There is a regression in 1.78.0 where compilation of the tvOS target (Tier 3) fails. It was working with 1.75.0 and 1.77.2 source distributions.

<details>
  <summary>config.toml</summary>

  ```toml
  profile = "library"
  
  [build]
  target = ["aarch64-apple-tvos-sim", "aarch64-apple-darwin"]
  docs = false
  locked-deps = true
  vendor = true
  extended = true
  tools = [
      "cargo"
  ]
  
  [install]
  prefix = "..."
  sysconfdir = "etc"
  
  [rust]
  channel = "stable"
  lto = "thin"
  ```
</details>

<details>
<summary>/usr/bin/xcrun --sdk appletvsimulator --run python3 x.py build</summary>

```
Building stage2 library artifacts (aarch64-apple-darwin -> aarch64-apple-tvos-sim)
...
error: methods `as_raw_stat`, `st_birthtime`, `st_birthtime_nsec`, `st_flags`, `st_gen`, and `st_lspare` are never used
  --> library/std/src/os/ios/fs.rs:29:8
   |
15 | pub trait MetadataExt {
   |           ----------- methods in this trait
...
29 |     fn as_raw_stat(&self) -> &raw::stat;
   |        ^^^^^^^^^^^
...
60 |     fn st_birthtime(&self) -> i64;
   |        ^^^^^^^^^^^^
61 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
62 |     fn st_birthtime_nsec(&self) -> i64;
   |        ^^^^^^^^^^^^^^^^^
...
68 |     fn st_flags(&self) -> u32;
   |        ^^^^^^^^
69 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
70 |     fn st_gen(&self) -> u32;
   |        ^^^^^^
71 |     #[stable(feature = "metadata_ext2", since = "1.8.0")]
72 |     fn st_lspare(&self) -> u32;
   |        ^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`

error: method `set_created` is never used
   --> library/std/src/os/ios/fs.rs:151:8
    |
148 | pub trait FileTimesExt: Sealed {
    |           ------------ method in this trait
...
151 |     fn set_created(self, t: SystemTime) -> Self;
    |        ^^^^^^^^^^^

error: could not compile `std` (lib) due to 2 previous errors
```
</details>
