### ISSUE TITLE
version 1.78.0 complie error

### ISSUE THREAD

**Issue by Arashimu** [rust-lang/rust#126074]
I use rustup to update the rust toolchain to version 1.78.0,but when I just use command "cargo new test" to build a simple project and then use cargo run , it always shows a error as follow:
``` txt
Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.78.0 (54d8815d0 2024-03-26)).
  Consider trying a newer version of Cargo (this may require the nightly release).
```
I change my Cargo.toml file as follow:
``` toml
cargo-features = ["edition2024"]

[package]
name = "marco"
version = "0.1.0"
edition = "2024"

[dependencies]
```
then it shows me another error :
``` txt
Caused by:
  the cargo feature `edition2024` requires a nightly version of Cargo, but this is the `stable` channel
```
so I use "rustup default nightly" to change the rust toolchain, and it shows me another problem again.
``` txt
Caused by:
  can't find `test_bin` bin at `src\bin\test_bin.rs` or `src\bin\test_bin\main.rs`. Please specify bin.path if you want to use a non-default path.
```
what can I say?
