### ISSUE TITLE
The config "test" is always ignored in [target.<cfg>] in config.toml.

### ISSUE THREAD

**Issue by heipiao233** [rust-lang/rust#126933]
I tried this code:

```toml
[target.'cfg(test)']
runner = "./run_test.sh"

[target.'cfg(not(test))']
runner = "./run.sh"
```

I expected to see this happen: When I run `cargo test`, it uses `./run_test.sh` as the runner, and when I run `cargo run`, it uses `./run.sh`

Instead, this happened: It always uses `./run.sh`

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (6b0f4b5ec 2024-06-24)
binary: rustc
commit-hash: 6b0f4b5ec3aa707ecaa78230722117324a4ce23c
commit-date: 2024-06-24
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```
