### ISSUE TITLE
When will the x86_64-win7-windows-msvc target be available for use?

### ISSUE THREAD

**Issue by fukyou-fukme** [rust-lang/rust#129053]
https://github.com/fukyou-fukme/clash-rs/actions
![r92zGHU7J20P1HaN4d](https://github.com/user-attachments/assets/03f99fa2-0bb2-4b8e-8897-bacd37c7d004)
![VfttwjZv3f6zhr731Rz](https://github.com/user-attachments/assets/ed0e819a-c9cf-4e00-a784-f804e356fb22)

**Comment by fukyou-fukme** [comment]
https://github.com/fukyou-fukme/clash-rs

**Comment by fukyou-fukme** [comment]
https://github.com/fukyou-fukme/clash-rs/actions

**Comment by ShE3py** [comment]
It seems like `tower` 0.4.13 requires `indexmap` 1.0.2 with the `std` feature, which is neither default nor requiered by `tower`'s `Cargo.toml`.

`tower`'s master branch has fixed the issue but it's not yet published, adding the feature explicitly may work :
```toml
# clash_lib/Cargo.toml
tower = { version = "0.4", features = ["util"] }
indexmap = { version = "1.0.2", features = ["std"] } # remove when tower 0.5 is published
```
