### ISSUE TITLE
build/bootstrap/.last-warned-change-id gets removed by workaround for #125578

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#130449]
`bootstrap.py` contains this snippet:

```python
                # FIXME: A cheap workaround for https://github.com/rust-lang/rust/issues/125578,
                # remove this once the issue is closed.
                bootstrap_out = self.bootstrap_out()
                if os.path.exists(bootstrap_out):
                    shutil.rmtree(bootstrap_out)

                p.map(unpack_component, tarballs_download_info)
```

when updating to a new `master`, bootstrap gets rebuilt, causing the "last warned change id" file to be deleted, so you see all the "new changes to x.py", even if there are no new changes to `x.py`.

**Comment by lolbinarycat** [comment]
We are deleting `.last-warned-change-id` again.

We probably want to write a regression test this time.

**Comment by Kobzol** [comment]
I wonder if we should just write that file to the source root and add it to `.gitignore`.. 🤔

**Comment by Kobzol** [comment]
Could you post some reproduction of how was the file deleted for you?

**Comment by lolbinarycat** [comment]
@Kobzol just running `./x clean` deletes it (but not `.rustc_info.json`, weirdly).

just tested and reproduced on bfc046a4b8d6b57db02540182466e989a9b0fb40

here's the config:
```toml
profile = "tools"  # Includes one of the default files in src/bootstrap/defaults
change-id = 143300

rust.debuginfo-level = 1
#rust.jemalloc = true
rust.download-rustc = false
rust.deny-warnings = false
build.docs-minification = false
#build.incremental = false
build.tidy-extra-checks = "auto:py"
```
