### ISSUE TITLE
rustdoc: list elements containing multiple paragraphs have confusing margins

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#130761]
take the feature flags on [the `time` crate](https://docs.rs/time/latest/time/).

![before](https://github.com/user-attachments/assets/fe54d8ee-8a1a-45fc-9434-2737c5c6f4d5)

the descriptions are grouped closer to the next element, instead of the one they actually apply to!

here's my simple fix:

```css
.docblock li {
  margin-bottom: .8em;
}

.docblock li p {
  margin-bottom: .1em;
}
```

here's what it looks like with this fix applied:

![after](https://github.com/user-attachments/assets/095be365-1bfc-4001-8664-59bc4125bb05)
