### ISSUE TITLE
Rust installs `i686-pc-windows-msvc` toolchain despite not specified anywhere

### ISSUE THREAD

**Issue by just-ero** [rust-lang/rust#132415]
### Description

I am trying to build Zed (https://github.com/zed-industries/zed) on Windows 11. I have followed the instructions at https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md.

I have only one toolchain installed:
```
> rustup toolchain list
stable-x86_64-pc-windows-msvc
```

When I try to run `cargo build --release`, Rust is installing the `1.81-i686-pc-windows-msvc` toolchain for no apparent reason:
```
> cargo build --release
info: syncing channel updates for '1.81-i686-pc-windows-msvc'
```
```
> rustup toolchain list
stable-x86_64-pc-windows-msvc
1.81-i686-pc-windows-msvc
```

Zed's `rust-toolchain.toml` also makes no mention of `i686`:
```toml
[toolchain]
channel = "1.81"
profile = "minimal"
components = [ "rustfmt", "clippy" ]
targets = [ "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "wasm32-wasip1", "x86_64-pc-windows-msvc" ]
```

It leads me to believe that there's something wrong with my system, but I absolutely cannot pinpoint what it might possibly be:
```
OS Name                          Microsoft Windows 11 Pro
Version                          10.0.22631 Build 22631
System Type                      x64-based PC
Processor                        AMD Ryzen 7 5800X 8-Core Processor, 4200 Mhz, 8 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM)  64.0 GB
```

**Comment by just-ero** [comment]
I've been losing my mind for a good 1-2 hours over this. It does indeed specify that toolchain:
```toml
default_host_triple = "i686-pc-windows-msvc"
default_toolchain = "nightly-i686-pc-windows-msvc"
profile = "default"
version = "12"

[overrides]
```

Why would this have happened? Can I just remove those first 2 lines?
