### ISSUE TITLE
running `rustdoc-js-std` tests does not rebuild rustdoc even if it is dirty

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#135590]
reproduction steps:
1. `./x test -v tests/rustdoc-js-std/return-based-sort.js` (or any other unit test in the folder, probably)
2. make a change to `search.js` (one that impacts the result of the test will make it more obvious)
3.  `./x test -v tests/rustdoc-js-std/return-based-sort.js` (again)

rustdoc will not get rebuilt.

workaround: do something like `./x doc library/core` to properly rebuild rustdoc

i've run into this a few times before but i only now figured out what was happening.

**Comment by onur-ozkan** [comment]
I can't reproduce this (HEAD is 7a202a9056ea19058a2a4b1b4f508f7f4ec3a0f6).

```sh
$ ./x test tests/rustdoc-js-std/return-specific.js
$ echo " " >> src/librustdoc/html/static/js/search.js
$ ./x test tests/rustdoc-js-std/return-specific.js (does the rebuild)
```

**Comment by lolbinarycat** [comment]
here's the contents of `config.toml`:

```toml
# Includes one of the default files in src/bootstrap/defaults
profile = "library"
change-id = 129176

[rust]
download-rustc = true
deny-warnings = false
[build]
patch-binaries-for-nix = true
submodules = true
docs-minification = false
[llvm]
download-ci-llvm = true
```
