### ISSUE TITLE
config.toml: Allow passing arbitrary configure and build args to LLVM cmake

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#138027]
LLVM's build system exposes a lot of flags that may be nice to tweak, but we probably don't want to worry about mapping directly in config.toml. It would be helpful to support something like the following:

```toml
[llvm]
configure-args = [
    "-DCMAKE_C_COMPILER_LAUNCHER=sccache",
    "-DCMAKE_CXX_COMPILER_LAUNCHER=sccache",
    "-DLLVM_OPTIMIZED_TABLEGEN=true",
    "-DBUILD_SHARED_LIBS=true", # unsure whether this would work with Rust
]
build-args = [
    # ...
]
```

These would get passed to `build_arg` and `configure_arg` on `cmake::Config`.
