### ISSUE TITLE
Crate features erroneously enabled when not default or specified

### ISSUE THREAD

**Issue by AdinAck** [rust-lang/rust#139219]
An MRE of this behavior involves a workspace with two crates: foo and bar.

The workspace manifest is simple:

```toml
[workspace]
resolver = "2"
members = [ "bar","foo"]
```

The crate `bar` has two features, "a" and "b":

```toml
[package]
name = "bar"
version = "0.1.0"
edition = "2024"

[features]
a = []
b = []
```

The crate `foo` depends on `bar` and enables the "a" feature:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2024"

[dependencies]
bar = { path = "../bar", features = ["a"] }
```

`foo` is a lib crate with no contents. `bar` is a lib/binary crate with only one check:

```rust
fn main() {
    #[cfg(all(feature = "a", feature = "b"))]
    compile_error!("Shouldn't happen.");
}
```

We never want the "a" and "b" features to be enabled at the same time.

From the workspace root, running `cargo b` works with no issue.
`cargo b -p foo`: no issue
`cargo b -p bar`: no issue
`cargo b -p bar --features b`: no issue
`cargo b --bin bar --features b`: error:

```
error: Shouldn't happen.
 --> bar/src/main.rs:3:5
  |
3 |     compile_error!("Shouldn't happen.");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Even though only the "b" feature was specified, the "a" feature is enabled.

If I `cd` into the `bar` directory and run `cargo b --bin bar --features b` there is no issue.

It appears that `foo`'s enabling of the "a" feature in `bar` is enabling that feature even when compiling `bar` independent of it's dependence usage in `foo`.

Interestingly, if we add the same check to `bar`'s `lib.rs`, the same command `cargo b --bin bar --features b` errors in `lib.rs` as well.

Of course, removing the "a" feature requirement where `foo` declares `bar` as a dependency results in no errors.

### Meta

`rustc --version --verbose`:
```
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: aarch64-apple-darwin
release: 1.85.1
LLVM version: 19.1.7
```
