### ISSUE TITLE
rustbook fails to compile on Fedora 42 with all dependencies met

### ISSUE THREAD

**Issue by Borgerr** [rust-lang/rust#141012]
### Summary

~~One dependency for building oniguruma related items are anything to do with libclang. This is currently insufficient for Fedora 42 x86 systems.~~ C23, used by default in systems like fedora 42, currently breaks rustbook builds. (see more [here](https://github.com/rust-lang/rust/issues/141012#issuecomment-2881150545)) This ends up being problematic as a dependency of rustbook is [mdbook-i18n-helpers](<https://github.com/google/mdbook-i18n-helpers#>), which does not compile well with this current setup.

Any previous version of `mdbook-i18n-helpers`, e.g. 3.6, 3.5, etc, does not compile, however, the latest activity on the head of their main branch does. Anything beyond this is speculative and should be discussed further below.

### Command used

```sh
./x doc
```

Also mimicked by compiling strictly `rustbook`.

### Expected behaviour

Documentation generation.

### Actual behaviour

Unable to compile onigumura.

### Bootstrap configuration (bootstrap.toml)
```toml
# See bootstrap.example.toml for documentation of available options
#
profile = "library"  # Includes one of the default files in src/bootstrap/defaults
change-id = 140732
```

### Operating system

Fedora 42

### HEAD

414482f6a0d4e7290f614300581a0b55442552a3

<details><summary>Build Log</summary>
<p>
My own build log is attached as a file ;)

[build.log](https://github.com/user-attachments/files/20211584/build.log)

</p>
</details>
