### ISSUE TITLE
FTBFS tarball rust 1.87.0: could not find native static library

### ISSUE THREAD

**Issue by rautyrauty** [rust-lang/rust#141120]
### Summary

The bug is not reproducible on 1.86.0.
Built from a tarball: curl -O https://static.rust-lang.org/dist/rustc-1.87.0-src.tar.gz

### Command used

All commands used are listed in the build log.

### Bootstrap configuration (bootstrap.toml)
```toml
change-id = 123711
[build]
cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
python = "python3"
submodules = false
docs = true
verbose = 2
vendor = true
extended = true
optimized-compiler-builtins = false
tools = ["cargo", "rust-analyzer", "clippy", "rustfmt", "src"]
build-stage = 2
test-stage = 2
doc-stage = 2

[install]
prefix = "/usr"

[rust]
channel = "stable"
download-rustc = false
codegen-tests = false
backtrace = true
jemalloc = false
rpath = false
debug = false
deny-warnings = false
debuginfo-level = 0
codegen-units = 2
lld = false

[llvm]
ninja = true
use-libcxx = false
download-ci-llvm = false
link-shared = true

[target.x86_64-unknown-linux-gnu]
cc = "clang"
cxx = "clang++"
ar = "llvm-ar"
ranlib = "llvm-ranlib"
llvm-config = "/usr/bin/llvm-config"
profiler = "/usr/lib/llvm-20.1/lib64/clang/20/lib/x86_64-unknown-linux-gnu/libclang_rt.profile.a"
```

### Operating system

ALT Linux Sisyphus

### HEAD

$ cat git-commit-hash 
17067e9ac6d7ecb70e50f92c1944e545188d2359

### Additional context
I am building an RPM package, I am the maintainer of the rust package in ALT Linux.

Build log:

[rust-1.87.0-FTBFS-build.log](https://github.com/user-attachments/files/20264530/rust-1.87.0-FTBFS-build.log)
