### ISSUE TITLE
x fmt panics with "no entry found for key" when I add an extra build target

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#141246]
### Summary

```
╭ ➜ ben@archlinux:~/rust
╰ ➤ x fmt
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.04s

thread 'main' panicked at src/bootstrap/src/lib.rs:1216:25:
no entry found for key
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/core/src/panicking.rs:269:5
   3: core::option::expect_failed
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/core/src/option.rs:2049:5
   4: core::option::Option<T>::expect
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/core/src/option.rs:958:21
   5: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/std/src/collections/hash/map.rs:1378:23
   6: bootstrap::Build::cc
             at ./src/bootstrap/src/lib.rs:1216:25
   7: bootstrap::core::sanity::check
             at ./src/bootstrap/src/core/sanity.rs:282:34
   8: bootstrap::Build::new
             at ./src/bootstrap/src/lib.rs:474:13
   9: bootstrap::main
             at ./src/bootstrap/src/bin/main.rs:99:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/5dadfd5c417f0b66816cb7ca662859e2c8751fb3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:00
```

### Bootstrap configuration (bootstrap.toml)
```toml
profile = "compiler"
change-id = 999999

[llvm]
assertions = true
download-ci-llvm = true

[rust]
download-rustc = false
deny-warnings = false
new-symbol-mangling = false
codegen-units-std = 1
debug-assertions = false
debug-logging = false
debuginfo-level = "line-tables-only"
debuginfo-level-std = 2
incremental = false
frame-pointers = true

[build]
target = ["x86_64-unknown-linux-gnu", "thumbv6m-none-eabi"]
```

### Operating system
```
Linux archlinux 6.14.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 09 May 2025 17:36:18 +0000 x86_64 GNU/Linux
```

### HEAD
`5f292eea6d63abbd26f1e6e00a0b8cf21d828d7d`
