### ISSUE TITLE
x.py clippy no longer works

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#142156]
### Command used

```sh
./x.py clippy
```

### Expected behaviour
clippy is run on the compiler.
this used to download a beta clippy and run it on the compiler

### Actual behaviour

This may no longer work as the required `cfg(bootstrap)` has been removed

```
Linting stage0 library {alloc, core, panic_abort, panic_unwind, proc_macro, std, sysroot, test, unwind} (x86_64-unknown-linux-gnu)
    Checking core v0.0.0 (/home/matthias/vcs/github/rust/library/core)
error: cannot find a built-in macro with name `autodiff_forward`
    --> library/core/src/macros/mod.rs:1536:5
     |
1536 | /     pub macro autodiff_forward($item:item) {
1537 | |         /* compiler built-in */
1538 | |     }
     | |_____^

error: cannot find a built-in macro with name `autodiff_reverse`
    --> library/core/src/macros/mod.rs:1554:5
     |
1554 | /     pub macro autodiff_reverse($item:item) {
1555 | |         /* compiler built-in */
1556 | |     }
     | |_____^
..
..
..
..


```

### Bootstrap configuration (bootstrap.toml)
```toml
change-id = 123711
[llvm]
download-ci-llvm = true
ninja = true
[build]
check-stage = 0
doc-stage = 0
build-stage = 1
test-stage = 1
dist-stage = 2
install-stage = 2
bench-stage = 2
extended = true
tools = [
    "cargo",
    "clippy",
    "rustdoc",
    "rustfmt",
    "rust-analyzer",
    "rust-analyzer-proc-macro-srv",
    "analysis",
    "src",
    "miri", "cargo-miri" # for dev/nightly channels
]
sanitizers = false
profiler = false
low-priority = true
[install]
[rust]
debug = true
download-rustc = false
codegen-units = 0
codegen-units-std = 0
debug-assertions=true
debuginfo-level = 2
lto = "off"
backtrace-on-ice = true
[target.x86_64-unknown-linux-gnu]
ar = "llvm-ar"
ranlib = "llvm-ranlib"
[dist]
```

### Operating system

Linux

### HEAD

c57119b9a1c86968188bb9703a7859c17f8bc71c

### Additional context

`x.py clippy --stage=1`
still works but would require re-bootstrapping compiler + clippy if we do a change to compiler source code
