### ISSUE TITLE
disable-minification is not forwarded to compiletest

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#142737]
### Summary

For documention built by `compiletest` directly, the `build.disable-minification` setting is ignored.

### Command used

```sh
./x test tests/rustdoc-js
```

### Expected behaviour

If `disable-minification` is set, this applies to all test suites, not just some of them.

### Actual behaviour

The `rustdoc-js` test suite always has minification enabled.

### Bootstrap configuration (bootstrap.toml)
```toml
profile = "tools"  # Includes one of the default files in src/bootstrap/defaults
change-id = 138986

rust.debuginfo-level = 1
rust.jemalloc = false
rust.download-rustc = false
rust.deny-warnings = false
build.docs-minification = false

```

### Operating system

Arch Linux

### HEAD
3bc767e1a215c4bf8f099b32e84edb85780591b1

### Additional context
This is an issue if an error occurs when running that test suite, as you won't get a meaningful line number.

The invocation site where ` --disable-minification` should be passed but isn't is at `compiletest::runtest::document`.
