### ISSUE TITLE
Rust-lang website looks blank on firefox/chrome.

### ISSUE THREAD

**Issue by a-jamesregan** [rust-lang/rust#24614]
All of the text on the webpage appears to be broken in both firefox and chrome.  Does your site need any special fonts?  I'm running the latest version of Arch linux.  I didn't install any extensions that would cause this on chrome and I didn't install any extensions on firefox.  I would like to point out that your site does work on the command line browser lynx.

Chrome:
![image](https://cloud.githubusercontent.com/assets/6695959/7221094/379bafcc-e6ac-11e4-8c72-4895915252a0.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/6695959/7221092/2802f002-e6ac-11e4-9c95-f38286177361.png)

**Comment by pnkfelix** [comment]
I assume it attempts to use the fonts listed in its style file, e.g.:

  http://www.rust-lang.org/css/style.css

```css
@font-face {
	font-family: 'Fira Sans';
	font-style: normal;
	font-weight: 300;
	src: local('Fira Sans Light'), url("../fonts/FiraSans-Light.woff") format('woff');
}
@font-face {
	font-family: 'Fira Sans';
	font-style: normal;
	font-weight: 400;
	src: local('Fira Sans'), url("../fonts/FiraSans-Regular.woff") format('woff');
}
@font-face {
	font-family: 'Fira Sans';
	font-style: normal;
	font-weight: 500;
	src: local('Fira Sans Medium'), url("../fonts/FiraSans-Medium.woff") format('woff');
}
...
```

Not sure why these entries would be causing a problem for you, though...
