### ISSUE TITLE
The titles in the official docs is not aligned to the body text

### ISSUE THREAD

**Issue by be5invis** [rust-lang/rust#32270]
![image](https://cloud.githubusercontent.com/assets/240091/13792645/cd6c8acc-eb2d-11e5-9c4f-de1bc83240d9.png)
![image](https://cloud.githubusercontent.com/assets/240091/13792724/470c464c-eb2e-11e5-90a6-a15794768728.png)

**Comment by nodakai** [comment]
According Chrome DevTools, it came from this section of `rust.css`

```css
h2 {
    font-size: 26px;
    padding: .2em .5em;
    border-bottom: 1px solid #ddd;
}
```

+1 to changing the left padding to zero
