### ISSUE TITLE
Rustc lies about linker not existing

### ISSUE THREAD

**Issue by ruuda** [rust-lang/rust#37420]
I am trying to cross compile an example in a crate for ARM. I cloned raspberrypi/tools into `~/repos/pi-tools` and then I put the following in my `~/.cargo/config`:

```toml
[target.arm-unknown-linux-gnueabihf]
linker = "/home/ruud/repos/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc-4.8.3"
```

In a Rust project of mine, I run

```
$ cargo build --verbose --target=arm-unknown-linux-gnueabihf --example my-example
```

This invokes rustc with among others these flags:

```
--target arm-unknown-linux-gnueabihf -C linker=/home/ruud/repos/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc-4.8.3
```

Rustc then complains:

```
error: could not exec the linker `/home/ruud/repos/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc-4.8.3`: No such file or directory (os error 2)
```

Note the “no such file or directory” error. However, the file definitely exists:

```
$ file /home/ruud/repos/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc-4.8.3
> /home/ruud/repos/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc-4.8.3: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.15, stripped
```

## Meta
```
$ rustc --version
> rustc 1.14.0-nightly (3caf63cc0 2016-10-24)
$ cargo --version
> cargo 0.13.0-nightly (9a0801d 2016-10-20)
```
My host OS is Linux on x64.
