### ISSUE TITLE
Provide a way to interpolate crate version in html_root_url

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#42300]
In Serde we work around this by having a reminder in Cargo.toml to update the html_root_url when releasing a new version. https://github.com/serde-rs/serde/commit/dc7ab2696a14fe5ca219ac09f8496bdc613ff602

```toml
[package]
version = "1.0.8" # remember to update html_root_url
```

```rust
#![doc(html_root_url = "https://docs.rs/serde/1.0.8")]
```

This is annoying and easily falls out of sync. For example mio 0.6.8 docs point to version 0.6.1: https://github.com/carllerche/mio/issues/613.

There should be a way to keep these synchronized automatically.
