### ISSUE TITLE
Source is missing from docs for crates that use a procedural macro

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#43371]
Running `./mach doc` on Servo's codebase yields a bunch of crates with the following warning:
```
warning: source code was requested to be rendered, but processing `<proc-macro source code>` had an error: No such file or directory (os error 2)
         skipping rendering of source code
```
This means that the source is available for [some types](http://doc.servo.org/constellation/constellation/struct.Constellation.html), but [not others](http://doc.servo.org/script/script_thread/struct.ScriptThread.html).

I'll try to figure out when this regressed.

**Comment by jdm** [comment]
Minimal reproduction:
```rust
extern crate heapsize;
#[macro_use] extern crate heapsize_derive;

#[derive(HeapSizeOf)]
pub struct Range<I>(I);
```
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]

[dependencies]
heapsize = "0.4"
heapsize_derive = "0.1"
```
