### ISSUE TITLE
LTO build emits debug symbols even with debug disabled

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#43392]
Even when building with `opt-level=3` and `debug=false`, rustc emits binaries with debug symbols.

I was experimenting with building a binary using `no_std`. My `Cargo.toml` looked like this:
```toml
[package]
name = "embedtest"
version = "0.1.0"
authors = ["Josh Triplett <josh@joshtriplett.org>"]

[profile.release]
panic = "abort"
lto = true

[dependencies]
libc = { version = "0.2", default-features = false }
```

`main.rs`:
```rust
#![no_std]
#![feature(lang_items, start)]

extern crate libc;

#[lang="panic_fmt"]
extern fn panic_fmt(_: ::core::fmt::Arguments, _: &'static str, _: u32) -> ! {
    loop {}
}

#[start]
fn start(_: isize, _: *const *const u8) -> isize {
    0
}
```

When built, this resulted in a 28408-byte binary. Checking with objdump showed the majority of that space in debug sections:

```
 25 .debug_pubnames 0000085b  0000000000000000  0000000000000000  0000102d  2**0
                  CONTENTS, READONLY, DEBUGGING
 26 .debug_info   000017d4  0000000000000000  0000000000000000  00001888  2**0
                  CONTENTS, READONLY, DEBUGGING
 27 .debug_abbrev 0000010a  0000000000000000  0000000000000000  0000305c  2**0
                  CONTENTS, READONLY, DEBUGGING
 28 .debug_line   000001bb  0000000000000000  0000000000000000  00003166  2**0
                  CONTENTS, READONLY, DEBUGGING
 29 .debug_frame  00000038  0000000000000000  0000000000000000  00003328  2**3
                  CONTENTS, READONLY, DEBUGGING
 30 .debug_str    000026c5  0000000000000000  0000000000000000  00003360  2**0
                  CONTENTS, READONLY, DEBUGGING
 31 .debug_macinfo 00000001  0000000000000000  0000000000000000  00005a25  2**0
                  CONTENTS, READONLY, DEBUGGING
 32 .debug_pubtypes 000001f2  0000000000000000  0000000000000000  00005a26  2**0
                  CONTENTS, READONLY, DEBUGGING
```

`strip` removed these (along with the symbol tables) and resulted in a 6040-byte binary.

I can reproduce this with nightly 1.20 from commit ae98ebfcb (for the example above), stable 1.17 (with a std-based hello world example), and stable 1.18 (likewise).

**Comment by nhynes** [comment]
I'm getting the same on 1.39-nightly. It makes for deceptively large wasm release builds (but at least there's great tooling for shrinking them :)

**Comment by bjorn3** [comment]
You can now use

```toml
[profile.release]
strip = "debuginfo"
```

in your `Cargo.toml` to strip debuginfo while linking. You can also use `strip = "symbols"` to also strip symbol names.
