### ISSUE TITLE
Add web-property-wide navigation to users.rust-lang.org

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#44503]
Originally posted [in the forum's meta section][post]. Copied here to keep it from getting lost.

[post]: https://users.rust-lang.org/t/add-web-property-wide-navigation-buttons-to-the-top/12649

CC @aturon

**Comment by notriddle** [comment]
Okay, here's how I did it on https://forum.bors.tech/

1. Go into the Admin / Customize / Themes section, and make a new theme to attach the header to. You're going to make it the forum's default theme when you're done, but you want to test it first.

    The "Admin" button is in the site menu, next to your user menu.

2. Click the Edit CSS/HTML button.

3. Paste this into the "Custom CSS" box:

```css
/* =============== Rust Header Menu CSS ================= */

span#rust-top-links {
    display: block !important;
    margin: 5px auto 0 auto;
    max-width: 1110px;
}
div#rust-navbar {
    z-index: 1040;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
}
.rust-nav-link-container li {
    display: inline-block;
    float: left;
}
.rust-nav-link-container a {
    text-decoration: none;
    color: #428bca;
    text-align: center;
    line-height: 48px;
    font-size: 14px;
    padding: 1em;
}
.rust-nav-link-container a.active {
    font-weight: bold;
}
.rust-nav-link-container a:hover,
.rust-nav-link-container a:active,
.rust-nav-link-container a:focus {
    text-decoration: underline;
    color: #2a6496;
}
.rust-nav-link-container {
    display: block;
    overflow: hidden;
    margin-left: 60px;
    position: absolute;
}
.navigation-topics #rust-navbar,
.navigation-categories #rust-navbar {
    position: fixed;
}
@media screen and (max-width: 800px) {
    .js div#rust-navbar {
        position: static;
        margin-top: -1em;
        margin-bottom: 1em;
    }
    .rust-nav-link-container {
        position: static;
        margin-left: 0;
    }
}
```

4. Paste this into the "After Header" box:

```html
<div id="rust-navbar">
<span id="rust-top-links">
<ul class="rust-nav-link-container">
   <li><a href="//www.rust-lang.org/en-US/">Home</a></li>
   <li><a href="//www.rust-lang.org/en-US/documentation.html">Documentation</a></li>
   <li><a href="//www.rust-lang.org/en-US/install.html">Install</a></li>
   <li><a href="//www.rust-lang.org/en-US/community.html" class="active">Community</a></li>
   <li><a href="//www.rust-lang.org/en-US/contribute.html">Contribute</a></li>
</ul></span>
</div>
```

5. After Saving it, you can click the "Preview" link to check out how it looks. You can customize this code to taste (it should be usable as-is, but it's up to you).

6. Go back to the main Theme Customization screen and make your new theme selectable by users and the default theme.

![Here's a preview of what this code looks like](https://user-images.githubusercontent.com/1593513/31027391-ebfbdef2-a4fe-11e7-9c15-cb3441e34f36.PNG)
