### ISSUE TITLE
Don't enforce snake_case for binary names

### ISSUE THREAD

**Issue by Majora320** [rust-lang/rust#45127]
Currently, if you have a Cargo.toml like this:

```toml
[package]
name = "some_package"
version = "0.0.0"

[[bin]]
name = "somePackage"
path = "src/main.rs"
```

rustc will complain:

```
warning: crate `somePackage` should have a snake case name such as `some_package`
  |
  = note: #[warn(non_snake_case)] on by default
```
I understand why this is reasonable for library crates, to enforce a common naming convention for rust libraries and source code. But it doesn't make much sense to enforce this for binaries as well, as there is no real advantage to doing so (note that the crate name isn't camelCase, only the binary name is).

---
```sh
$ rustc --version
rustc 1.22.0-nightly (05f8ddc46 2017-10-07)
```
