### ISSUE TITLE
Misleading E0210: "only traits defined in the current crate can be implemented for a type parameter"

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#46210]
```
$ rustc --version
rustc 1.23.0-nightly (45594d5de 2017-11-22)
```

```toml
[package]
name = "type-param"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[dependencies]
# apologies for the heavy dependency; this can probably be minimized
# but when I tried to do this I got the (slightly more accurate) E0117 instead
nalgebra = "0.13"
```

```rust
extern crate nalgebra;
use nalgebra::{Scalar, Dim, U3, MatrixMN};

struct Rows3<X, R>(MatrixMN<X, R, U3>);

// error[E0210]: type parameter `X` must be used as the type parameter for some local type
// (e.g. `MyStruct<T>`); only traits defined in the current crate can be implemented for
// a type parameter
impl<X: Scalar, R: Dim> From<Rows3<X, R>> for MatrixMN<X, R, U3> {
    fn from(rows: Rows3<X, R>) -> Self
    { rows.0 }
}

fn main() { }
```

The wording of the error seems to suggest that I have written `impl<...> From<...> for X`, which I clearly have not.  (Also, on the surface, I *have* used `X` as the type parameter for a local type; just perhaps not in the way that the error message had intended)
