### ISSUE TITLE
It is not obvious that the paint brush is the theme switcher in rustdoc nightly

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#47735]
At least 2 people (someone else and me) got confused by the dark theme and couldn't find the setting to put back the light one.

<s>Btw, I wonder why https://doc.rust-lang.org/nightly/std suddenly switched to the dark one here, surely the dark one isn't the new default, right…?</s> Seems like "main" is indeed the default one, ignore this part.

**Comment by shingtaklam1324** [comment]
It seems pretty clear to me that the brush is the theme change button. However, I can see where the ambiguity would come from. The problem is with the design of the page, for example, on my 1920*1080 screen, the rendered image is only 17px*17px, which seriously limits the available designs. 

Also the design of the web page currently having the theme switch being a drop down instead of a toggle switch means that switches like [this](https://github.com/shingtaklam1324/cdn/blob/master/svg/dark.svg) and [this](https://github.com/shingtaklam1324/cdn/blob/master/svg/light.svg) won't work.

**Comment by steveklabnik** [comment]
This was used to be consistent with https://doc.rust-lang.org/book/second-edition/

**Comment by kennytm** [comment]
Some UX comments on the paint brush:

1. The border is too distracting. Please remove it. 

    ```css
    #theme-picker { border: none; }
    ```

2. The background is very distracting too. But we can't remove the background color because the paint brush is always black. Why are we serving it using an `<img>`? It should be the `background` itself so you could use a white paint brush in dark mode.

    ```css
    #theme-picker {
      background: url('../../brush.svg') no-repeat center;
      background-size: 17px;
    }
    ```

    Or it can even be an icon font like mdbook.

3. If it is going to be consistent with mdbook, the hover effect should adjust the paint brush's text color (or opacity), not the border color. I find that the mdbook effect looks better.

    ```css
    #theme-picker { opacity: 0.25 }
    #theme-picker:hover { opacity: 1 }    
    ```

4. The drop down does not disappear after changing a theme (unlike a system drop down). It does not disappear when clicking outside either (unlike mdbook). You need to click the paint brush again to close it, which is very unintuitive.
