### ISSUE TITLE
codegen-units + ThinLTO is not as good as codegen-units = 1

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#47745]
We recently had a fair amount of reports about code generation quality drop. One of the recent causes for the quality drop is the enablement of codegen-units and ThinLTO.

It seems that ThinLTO is not capable of producing results matching those obtained by compiling without codegen-units in the first place.

The list of known reports related follows:

* https://github.com/rust-lang/rust/issues/47665
* https://github.com/rust-lang/rust/issues/47561
* https://github.com/rust-lang/rust/issues/47356
* https://github.com/rust-lang/rust/issues/47062 (specifically this [comment](https://github.com/rust-lang/rust/issues/47062#issuecomment-360449227))

Improvements to ThinLTO quality are inbound with the soon-to-happen LLVM upgrade(s), however those do not help sufficiently, it would be nice to figure out why ThinLTO is not doing good enough job.

cc @alexcrichton @nikomatsakis

**Comment by nikomatsakis** [comment]
Thanks for filing this @nagisa =)

**Comment by alexcrichton** [comment]
Indeed thanks! I'll try to take a closer look at this when we've upgraded LLVM

**Comment by matthiaskrgr** [comment]
By the way there is a great talk about how thinlto is designed here: https://www.youtube.com/watch?v=p9nH2vZ2mNo in case people are curious. :)

**Comment by robsmith11** [comment]
Matrix multiplication is slower with thinlto + multiple codege-units using https://github.com/bluss/matrixmultiply .

I can create a minimal example if needed.

**Comment by johnthagen** [comment]
I've always thought that there should be another [Cargo profile](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections), something like:

```toml
# The publish profile, used for `cargo build --publish`.
[profile.publish]
# (...) everything else the same as profile.release except:
lto = true        # Enable full link-time optimization.
codegen-units = 1 # Use only 1 codegen-unit to enable full optimizations.
```

Because I feel like there should be a distinction between release builds the developer compiles on their local machine during development (not debug builds, but "fast" release builds) and truly publishable builds (like, for example the version of Firefox that is released for public consumption) in which case sacrificing build time once is more acceptable.
