### ISSUE TITLE
LTO ignored for all crate types when building multiple crate types and one doesn't support it

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust#51009]
https://github.com/rustwasm/rust_wasm_template has

```toml
[lib]
crate-type = [
  # Build a cdylib to make a `.wasm` library.
  "cdylib",
  # Build an rlib for testing and benching.
  "rlib"
]

[profile.release]
lto = true
```

The `lto = true` is ignored for everything because rlibs don't support LTO. I would expect that the cdylib has LTO and that only the rlib ignores the LTO options.

@alexcrichton tells me this is a rust compiler bug, not a cargo bug.

FWIW, this command does not work either:

```
cargo rustc -- -C lto=fat --crate-type cdylib
```
