### ISSUE TITLE
Rustdoc cann't build rust documentation with custom libdir.

### ISSUE THREAD

**Issue by o01eg** [rust-lang/rust#52317]
Looks like something related to https://github.com/rust-lang/rust/issues/45345

```
 Documenting core v0.0.0 (file:///tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libcore)
     Running `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustdoc --crate-name core libcore/lib.rs --target x86_64-unknown-linux-gnu -o /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/doc -L dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps`
rustdoc command: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "--crate-name" "core" "libcore/lib.rs" "--target" "x86_64-unknown-linux-gnu" "-o" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/doc" "-L" "dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps" "-L" "dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps" "--cfg" "stage1" "--cfg" "dox" "--sysroot" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1" "-Z" "force-unstable-if-unmarked" "--linker" "x86_64-pc-linux-gnu-gcc" "-Z" "unstable-options" "-Z" "unstable-options" "--crate-version" "1.29.0-dev (d334027c5 2018-07-12)"
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc: error while loading shared libraries: librustc_driver-8d7fdf72b3fbbc6b.so: cannot open shared object file: No such file or directory
error: Could not document `core`.

Caused by:
  process didn't exit successfully: `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustdoc --crate-name core libcore/lib.rs --target x86_64-unknown-linux-gnu -o /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/doc -L dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps` (exit code: 127)


command did not execute successfully: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "doc" "--target" "x86_64-unknown-linux-gnu" "-j" "1" "-v" "--release" "--locked" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libstd/Cargo.toml" "--no-deps" "-p" "alloc" "-p" "core" "-p" "std" "-p" "std_unicode"
expected success, got: exit code: 101
```

but file exists: 
```
$ find /tmp/portage/ -name librustc_driver-8d7fdf72b3fbbc6b.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/lib64/rust-9999/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-8d7fdf72b3fbbc6b.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-8d7fdf72b3fbbc6b.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1/lib64/rust-9999/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-8d7fdf72b3fbbc6b.so
/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-8d7fdf72b3fbbc6b.so
```

config.toml:
```toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
targets = "X86;Mips;NVPTX;BPF;AArch64"
[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["i686-unknown-linux-gnu","x86_64-unknown-linux-gnu","wasm32-unknown-unknown"]
docs = true
submodules = false
python = "python2.7"
locked-deps = true
vendor = false
verbose = 2
sanitizers = true
extended = true
tools=["src", "rls", "analysis", "rustfmt", "clippy"]
[install]
prefix = "/usr"
libdir = "lib64/rust-9999"
docdir = "share/doc/rust-9999"
mandir = "share/rust-9999/man"
[rust]
optimize = true
debuginfo = false
debug-assertions = false
use-jemalloc = true
default-linker = "x86_64-pc-linux-gnu-gcc"
rpath = false
ignore-git = false
lld = true
llvm-tools = true
[target.i686-unknown-linux-gnu]
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ar = "x86_64-pc-linux-gnu-ar"
[target.x86_64-unknown-linux-gnu]
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ar = "x86_64-pc-linux-gnu-ar"
[target.wasm32-unknown-unknown]
```

Affected rust version: 2d5a295d518b499360ec05df5447351a1e325846

Known to work revision: 478226cc2ab768d45cc8284652c5997559b7b05f
