### ISSUE TITLE
thumbv7em-none-eabi build with no-std fails with missing references to standard library functions

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#52725]
```fish
mqudsi@Blitzkrieg /m/d/G/r/cortex-m-quickstart> rustc --version
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
mqudsi@Blitzkrieg /m/d/G/r/cortex-m-quickstart> cargo --version
cargo 1.29.0-nightly (506eea76e 2018-07-17)
mqudsi@Blitzkrieg /m/d/G/r/cortex-m-quickstart> arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Attempting to compile the `hello.rs` example from the `cortex-m-quickstart` crate without xargo after `rustup target add thumbv7em-none-eabi`:

```fish
mqudsi@Blitzkrieg /m/d/G/r/cortex-m-quickstart>
env (env |sed '/^\(PATH\|HOME\|PWD\|USER\)/b;s/=.*/=/g') cargo build --example hello --target thumbv7em-none-eabi
   Compiling vcell v0.1.0
   Compiling bare-metal v0.2.0
   Compiling aligned v0.2.0
   Compiling r0 v0.2.2
   Compiling cortex-m-semihosting v0.3.0
   Compiling volatile-register v0.2.0
   Compiling cortex-m-rt v0.5.1
   Compiling cortex-m v0.5.2
   Compiling panic-semihosting v0.3.0
   Compiling cortex-m-quickstart v0.3.2 (file:///mnt/d/GIT/rustcortex/cortex-m-quickstart)
error: linking with `arm-none-eabi-gcc` failed: exit code: 1
  |
  = note: "arm-none-eabi-gcc" "-L" "/home/mqudsi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/thumbv7em-none-eabi/lib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/examples/hello-2e4ab7277541a4c5.16u6js6g0l3k1ic6.rcgu.o" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/examples/hello-2e4ab7277541a4c5.3l0398fjltevyo2h.rcgu.o" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/examples/hello-2e4ab7277541a4c5.4xq48u46a1pwiqn7.rcgu.o" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/examples/hello-2e4ab7277541a4c5.544l4wfz89vbhoea.rcgu.o" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/examples/hello-2e4ab7277541a4c5.8xzrsc1ux72v29j.rcgu.o" "-o" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/examples/hello-2e4ab7277541a4c5" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/debug/deps" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/build/cortex-m-quickstart-2ffd5f18bb7dccbd/out" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/build/cortex-m-d10fc233ba5cdde4/out" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/build/cortex-m-rt-58a8c9b30748ebc9/out" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/build/cortex-m-rt-58a8c9b30748ebc9/out" "-L" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/build/cortex-m-semihosting-c3793594fbee2f1e/out" "-L" "/home/mqudsi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/thumbv7em-none-eabi/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libpanic_semihosting-c0c60999560899c9.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libcortex_m-28e4aedd6ab537f5.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libvolatile_register-77c52ea100a229e1.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libvcell-2d535a4f29ff87af.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libbare_metal-49c8e733c6ec9713.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libaligned-6534e90a0ad3fa07.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libcortex_m_semihosting-fe101d1603d37137.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libcortex_m_rt-82216ff9b050a0f8.rlib" "/mnt/d/GIT/rustcortex/cortex-m-quickstart/target/thumbv7em-none-eabi/debug/deps/libr0-3132ffbfc74c8f3e.rlib" "/home/mqudsi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/thumbv7em-none-eabi/lib/libcore-f30fde47d896be92.rlib" "-Wl,--end-group" "/home/mqudsi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/thumbv7em-none-eabi/lib/libcompiler_builtins-b77dbe465d544924.rlib" "-Wl,-Bdynamic"
  = note: /usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/lib/crt0.o: In function `_start':
          /build/newlib-5zwpxE/newlib-2.2.0+git20150830.5a3d536/build/arm-none-eabi/libgloss/arm/../../../../libgloss/arm/crt0.S:419: undefined reference to `atexit'
          /build/newlib-5zwpxE/newlib-2.2.0+git20150830.5a3d536/build/arm-none-eabi/libgloss/arm/../../../../libgloss/arm/crt0.S:421: undefined reference to `__libc_init_array'
          /build/newlib-5zwpxE/newlib-2.2.0+git20150830.5a3d536/build/arm-none-eabi/libgloss/arm/../../../../libgloss/arm/crt0.S:427: undefined reference to `exit'
          /build/newlib-5zwpxE/newlib-2.2.0+git20150830.5a3d536/build/arm-none-eabi/libgloss/arm/../../../../libgloss/arm/crt0.S:427: undefined reference to `__libc_fini_array'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `cortex-m-quickstart`.
```

**Comment by hellow554** [comment]
Looks like you are missing the `.cargo/config` file, or at least `-nostartfiles` ?

**Comment by mqudsi** [comment]
Thanks for the reply, @hellow554 but the `.cargo/config` file is present:

```toml
[target.thumbv6m-none-eabi]
runner = 'arm-none-eabi-gdb'
rustflags = [
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",

  # uncomment to use rustc LLD to link programs (a)
  # "-C", "link-arg=-Tlink.x",
  # "-C", "linker=lld",
  # "-Z", "linker-flavor=ld.lld",
]

[target.thumbv7m-none-eabi]
runner = 'arm-none-eabi-gdb'
rustflags = [
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",

  # uncomment to use rustc LLD to link programs (a)
  # "-C", "link-arg=-Tlink.x",
  # "-C", "linker=lld",
  # "-Z", "linker-flavor=ld.lld",
]

[target.thumbv7em-none-eabi]
runner = 'arm-none-eabi-gdb'
rustflags = [
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",

  # uncomment to use rustc LLD to link programs (a)
  # "-C", "link-arg=-Tlink.x",
  # "-C", "linker=lld",
  # "-Z", "linker-flavor=ld.lld",
]

[target.thumbv7em-none-eabihf]
runner = 'arm-none-eabi-gdb'
rustflags = [
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",

  # uncomment to use rustc LLD to link programs (a)
  # "-C", "link-arg=-Tlink.x",
  # "-C", "linker=lld",
  # "-Z", "linker-flavor=ld.lld",
]

# (a) you also need to comment out the other two `link-arg` lines. But note that as of v0.6.0 LLD
# has a bug where it mislinks FFI calls and they up crashing the program at runtime
# [build]
# target = "thumbv7em-none-eabi"
```
