### ISSUE TITLE
x.py: config.toml's codegen-units overridden by RUSTFLAGS

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#53658]
(edit: it's actually not ignored, just overridden by `RUSTFLAGS` being set, see https://github.com/rust-lang/rust/issues/53658#issuecomment-417164753 and below)

When trying to reduce the memory usage of building rustc (trying to build, even with `python x.py build -j 1`, results in OOM in my system with ~4G free RAM), I tried to turn on `codegen-units=1`: (ignoring commented and empty lines)
```toml
[llvm]
assertions = true
[build]
[install]
[rust]
codegen-units = 1
debug-assertions = true
debuginfo = true
debuginfo-tools = true
[target.x86_64-unknown-linux-gnu]
[dist]
```

However, in the error, due to OOM (it apparently didn't work), I see `-Ccodegen-units=10`, so I guess it's not respecting the codegen-units value in `config.toml`.

This happens at step `Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)` / `Compiling rustc v0.0.0`, and I get `process didn't exit successfully: […] -Ccodegen-units=10 […]`
