### ISSUE TITLE
docs.rs css issues with rustdoc (responsiveness)

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust#55883]
docs.rs and rustdoc aren't playing nicely together as we can see here (it's pretty much broken):

![docsrs](https://user-images.githubusercontent.com/5961244/48321831-9e122300-e624-11e8-9f38-6085fe7aa3fb.png)

To fix this, we should modify the selector from `body > .sidebar` to `.rustdoc > .sidebar`.

https://github.com/rust-lang/rust/blob/775eab58835f9bc0f1f01ccbb79725dce0c73b51/src/librustdoc/html/static/rustdoc.css#L959-L967

After:

![docsrs_after](https://user-images.githubusercontent.com/5961244/48322057-d82ff480-e625-11e8-8d26-047547952343.png)

By futher modifying docs.rs's css with something like:

```css
@media (max-width: 700px) {
    div.rustdoc {
        padding-top: 0;
    }
    div.rustdoc .sidebar {
        padding-top: 0 !important;
    }
    #sidebar-filler {
        display: none;
    }
}
```

Final:

![docsrs_final](https://user-images.githubusercontent.com/5961244/48322422-c3ecf700-e627-11e8-9c28-f89506b14834.png)
