### ISSUE TITLE
Allowing different opt-level for different crates of the workspace

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#56454]
I have two crates in a workspace: backend server and wasm frontend (and a shared crate for the API types).
I want to use the following profile only for the `frontend` crate:
```toml
[profile.release]
lto = true
opt-level = "z"
```

I only want to optimize my frontend for size, but the backend server for speed.

But:
> warning: profiles for the non root package will be ignored, specify profiles at the workspace root

Why can't this be allowed?

I'd really like to avoid having to split the frontend off into a separate workspace, is there a solution?

**Comment by ehuss** [comment]
There is an unstable, nightly-only feature to allow you to do this, see https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-overrides

In this case you would add something like this to your workspace:
```toml
[profile.release.overrides.frontend]
lto = true
opt-level = "z"
```
