### ISSUE TITLE
attributes on struct field expressions are lost in TokenStream.to_string

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#56879]
## Simplified report

I originally thought that nested proc macros were required to hit this bug but it turned out they were not required.

### STR

- crate: macros

``` toml
[package]
name = "macros"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "=0.6.10"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "=0.15.23"
```

``` rust
extern crate proc_macro;

use proc_macro::TokenStream;
use syn::{parse_macro_input, ItemFn};

use quote::quote;

#[proc_macro_attribute]
pub fn foo(_: TokenStream, input: TokenStream) -> TokenStream {
    panic!("{}", input);
}
```

- crate: foo

``` toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[dependencies]
macros = { path = "macros" }
```

``` rust
use macros::foo;

#[foo]
fn foo() {
    pub struct Foo {
        x: i32,
        y: i32,
        #[cfg(never)] // PRESERVED (field def)
        z: i32,
    }

    #[allow(dead_code)] // PRESERVED (item)
    fn bar() {}

    #[allow(dead_code)] // PRESERVED (expr)
    let x = Foo {
        x: 0,
        y: 1,
        #[cfg(never)] // LOST (field expr)
        z: 2,
    };
}
```

Note how the attribute on `z: 2` is lost when stringifying the `TokenStream`.

``` console
$ cargo build
error: custom attribute panicked
 --> src/lib.rs:3:1
  |
3 | #[foo]
  | ^^^^^^
  |
  = help: message: fn foo() {
              pub struct Foo {
                  x: i32,
                  y: i32,
                  #[cfg(never)]
                  z: i32,
              }
              #[allow(dead_code)]
              fn bar() { }
              #[allow(dead_code)]
              let x = Foo{x: 0, y: 1, z: 2,};
          }

error: aborting due to previous error
```

---

## Original report

attributes on fields are lost in nested proc macros

### STR

- crate: macros

``` toml
[package]
name = "macros"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "=0.6.10"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "=0.15.23"
```

``` rust
extern crate proc_macro;

use proc_macro::TokenStream;
use syn::{parse_macro_input, ItemFn};

use quote::quote;

#[proc_macro_attribute]
pub fn foo(_: TokenStream, _: TokenStream) -> TokenStream {
    let ts: TokenStream = quote!(
        #[id]
        fn foo() {
            #[allow(dead_code)] // PRESERVED (item)
            fn bar() {}

            #[allow(dead_code)] // PRESERVED (expr)
            let foo = Foo {
                x: 0,
                y: 1,
                #[cfg(never)] // LOST (field)
                z: 2,
            };
        }
    )
    .into();

    eprintln!("foo -> {}\n", ts);
    ts
}

#[proc_macro_attribute]
pub fn id(_: TokenStream, input: TokenStream) -> TokenStream {
    eprintln!("id <- {}", input.to_string());

    let input = parse_macro_input!(input as ItemFn);
    quote!(#input).into()
}
```

- crate: foo

``` toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[dependencies]
macros = { path = "macros" }
```

``` rust
use macros::{foo, id};

pub struct Foo {
    x: i32,
    y: i32,
}

#[foo]
const FOO: () = {};
```

I expect `foo` to compile with `cargo build` (no `--cfg` passed) but it doesn't:

``` console
$ # note that `#[cfg]` is missing in the `id <- ..` output
$ cargo build
foo -> # [ id ] fn foo (  ) {
# [ allow ( dead_code ) ] fn bar (  ) {  } # [ allow ( dead_code ) ] let foo =
Foo { x : 0 , y : 1 , # [ cfg ( never ) ] z : 2 , } ; }

id <- fn foo() {
    #[allow(dead_code)]
    fn bar() { }
    #[allow(dead_code)]
    let foo = Foo{x: 0, y: 1, z: 2,};
}
error[E0560]: struct `Foo` has no field named `z`
  |
  = note: available fields are: `x`, `y`

error: aborting due to previous error
```

If I remove `#[id]` from `fn foo()` then the crate `foo` compiles.

Note that the attribute on field `z` is lost even if it's not a `#[cfg]` attribute.

### Meta

``` console
$ rustc -V
rustc 1.33.0-nightly (93c2f055b 2018-12-15)
```

---

It seems that the attribute is only lost when going from `TokenStream` to a `String`. If I don't roundtrip through `syn::TokenStream` then the code behaves as expected:

``` rust
// ..

#[proc_macro_attribute]
pub fn id(_: TokenStream, input: TokenStream) -> TokenStream {
    eprintln!("id <- {}", input.to_string());
    input // no roundtrip
}
```

``` console
$ # works as expected
$ # but note that `#[cfg(never)]` is not shown here in `id <- ..`
$ cargo build && echo OK
foo -> # [ id ] fn foo (  ) {
# [ allow ( dead_code ) ] fn bar (  ) {  } # [ allow ( dead_code ) ] let foo =
Foo { x : 0 , y : 1 , # [ cfg ( never ) ] z : 2 , } ; }

id <- fn foo() {
    #[allow(dead_code)]
    fn bar() { }
    #[allow(dead_code)]
    let foo = Foo{x: 0, y: 1, z: 2,};
}
OK

$ cargo rustc -- --cfg never
error[E0560]: struct `Foo` has no field named `z`
 --> src/lib.rs:8:1
  |
8 | #[foo]
  | ^^^^^^ `Foo` does not have this field
  |
  = note: available fields are: `x`, `y`
```

cc @alexcrichton @petrochenkov
