### ISSUE TITLE
Bundled clippy is built with incorrect sysroot

### ISSUE THREAD

**Issue by o01eg** [rust-lang/rust#57117]
See https://github.com/rust-lang/rust-clippy/issues/2874

Clippy is compiled with `SYSROOT` environment variable is `""` while correct value should be `"/usr"`

config.toml:
```toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
targets = "X86;Mips;NVPTX;BPF;AArch64"
[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu"]
docs = false
submodules = false
python = "python2.7"
locked-deps = true
vendor = false
verbose = 2
sanitizers = false
extended = true
tools = ["clippy",]
[install]
prefix = "/usr"
libdir = "lib64/rust-9999"
docdir = "share/doc/rust-9999"
mandir = "share/rust-9999/man"
[rust]
optimize = true
debuginfo = false
debug-assertions = true # false
jemalloc = true
default-linker = "x86_64-pc-linux-gnu-gcc"
rpath = false
ignore-git = false
lld = false
llvm-tools = true
[target.x86_64-unknown-linux-gnu]
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ar = "x86_64-pc-linux-gnu-ar"
```

OS: Gentoo Linux AMD64
