### ISSUE TITLE
Cargo stripping out metadata and pre-release from local dependencies' versions

### ISSUE THREAD

**Issue by anhbakhia** [rust-lang/rust#57777]
Hello Rust developers,

I'm using Rust 1.32.0.

For example I have a local dependency with version `0.1.0+meta-pre`. And my _Cargo.toml_ is:

```toml
[dependencies]
some-lib = { version="0.1.0+meta-pre", path="..." }
```

However in _Cargo.lock_, metadata and pre-release are stripped out.

Would you confirm that this is intended, or this is a bug? In any case, I think those (metadata and pre-release) should be kept as-is.

Thank you,
