### ISSUE TITLE
Cargo: support for local relative paths of Git repositories

### ISSUE THREAD

**Issue by anhbakhia** [rust-lang/rust#57790]
Hello Rust developers,

Currently this sample of _Cargo.toml_ doesn't work:

```toml
[dependencies]
some-lib = { git='file:../../some-lib/', tag='0.1.0' }
```

If I change to full path, it will work. However using local full paths is not useful while sharing code with team.

Would you consider adding support for local Git relative paths?

Thank you,
