### ISSUE TITLE
Is there a way to get notified when feature becames stable?

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#58179]
In my personal projects I use stable compiler and prefer not to switch to nightly. There are few lines in my code like this:
```
// TODO: Use foo, when foo becames stable /*link to github*/
// Commented code
```

I usually use some workaround before feature becames stable. Is there an annotation or something which will give me warning, when feature became stable and encourage me to update my code?

It seems for me, good addition to have.

**Comment by nagisa** [comment]
Subscribe to the corresponding [`C-tracking-issue`](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AC-tracking-issue) issues.

**Comment by nagisa** [comment]
Oh and the Rust compiler *will* warn for most features that have been stabilised but still have a corresponding unnecessary `#![feature(...)]`. [Example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7dc4735ee496eaf6161a124b6b59b35f).

**Comment by In-line** [comment]
Hey, thanks for the response, but IMHO I don't agree with the idea of closing this issue.

1) Subscribing to the C-tracking-issue issues and manually checking code for updates is a bad idea. I'm asking about automatic solution.
2) I don't use nightly and code requiring feature in the most cases isn't written. A workaround is used.
3) This is the example, hypothetic use of the annotation I desire.

```
#[maybe_feature(some_feature)]
fn example() { /*....*/ }
```

Prints nothing on stable, when feature becames stable it prints.
```
Warning: the feature `some_feature` has been stable since 1.26.0```

**Comment by In-line** [comment]
Friendly ping @nagisa

**Comment by abonander** [comment]
> Subscribe to the corresponding [`C-tracking-issue`](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AC-tracking-issue) issues.

Given how much discussion can occur in some of these tracking issue threads, this is probably too noisy to be useful for someone who's just interested in the stability status.

I second using the `feature` flag to watch the status but it'll really only provide consistent updates if you're testing the project in CI, otherwise you have to remember to build under the nightly compiler from time to time if you prefer stable like @In-line. You can use `cfg_attr` and a Cargo feature so that it doesn't always require nightly at least:

```rust
// `nightly` is not a special feature name but it's sort-of the convention
#![cfg_attr(feature = "nightly", feature(...))]
```

You can also add `#![deny(stable_features)]` to trigger a lint error for stabilized features so it "breaks" the build and notifies you (if you have Travis-CI set up to do that).

Travis-CI will build open-source projects for free regardless of if they're published on Crates.io. It's relatively easy to configure as well. Here's a basic `.travis.yml` assuming you're using `nightly` as your Cargo feature for this:

```yaml
language: rust
rust:
  - stable
  - nightly
matrix:
  # this prevents the entire repostory's build status from being marked as failed
  # it depends on whether you want stabilized features to loudly notify you or not
  - allow_failures:
      - rust: nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  # this is how we test the `nightly` feature
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo build --features "nightly"; fi
```
