### ISSUE TITLE
Criterion benchmarks hang with target-cpu=znver1

### ISSUE THREAD

**Issue by novacrazy** [rust-lang/rust#65618]
On my system, a Zen 1 AMD CPU, attempting to run Criterion benchmarks with `RUSTFLAGS = "-C target-cpu=znver1"` results in the benchmark hanging at the `Analyzing` stage for a few minutes before I killed the program.

Without the flags, it doesn't hang at all, as expected.

This affects stable, beta and nightly, and is probably related to LLVM 9.

Code that can hang on stable:
```rust
#[macro_use]
extern crate criterion;

use criterion::{Criterion, ParameterizedBenchmark};

fn criterion_benchmark(c: &mut Criterion) {
    c.bench(
        "bench",
        ParameterizedBenchmark::new(
            "old",
            |b, _| {
                b.iter(|| {});
            },
            vec![()],
        )
        .with_function("new", |b, _| {
            b.iter(|| {});
        }),
    );
}

criterion_group!(my_benches, criterion_benchmark);
criterion_main!(my_benches);
```

using `cargo +stable bench`

No special flags are present in the `Cargo.toml`

```toml
[package]
name = "bench-test"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "benchmark_name"
harness = false
```
