### ISSUE TITLE
Rust produces invalid Wasm global variables

### ISSUE THREAD

**Issue by PiotrSikora** [rust-lang/rust#65987]
It looks that Rust is producing WebAssembly Global variables which value is the offset in the linear memory to where the value of the Global variable is stored, instead of the value itself.

From my chat with @jakobkummerow, it seem that this is invalid behavior, since Global variables can be stored outside of the linear memory, so it looks that Rust is not adhering to the spec.
```
$ cat test_rust.rs
```
```
#[no_mangle]
pub static TEST: u32 = 0xAABBCCDD;
```
```
$ rustc -C link-arg=-S --crate-type cdylib --target wasm32-unknown-unknown test_rust.rs
```
```
$ wasm-objdump -x test_rust.wasm 
```
```
test_rust.wasm: file format wasm 0x1

Section Details:

Table[1]:
 - table[0] type=funcref initial=1 max=1
Memory[1]:
 - memory[0] pages: initial=17
Global[4]:
 - global[0] i32 mutable=1 - init i32=1048576
 - global[1] i32 mutable=0 <__data_end> - init i32=1048580
 - global[2] i32 mutable=0 <__heap_base> - init i32=1048580
 - global[3] i32 mutable=0 <TEST> - init i32=1048576
Export[4]:
 - memory[0] -> "memory"
 - global[1] -> "__data_end"
 - global[2] -> "__heap_base"
 - global[3] -> "TEST"
Data[1]:
 - segment[0] size=4 - init i32=1048576
  - 0100000: ddcc bbaa                                ....
Custom:
 - name: "producers"
```
In the above example, Global variable `TEST` has the value `1048576`, which is not the value of the variable in the source code, but an offset in the linear memory that contains `0xAABBCCDD`.

Please note that both `__data_end` and `__heap_base` Global variables contain the value, and not the offset in the linear memory, so this behavior is inconsistent.
