### ISSUE TITLE
Rustdoc hang with watt patched proc_macro2 in syn

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#68017]
cc @dtolnay 

Full repro: <https://github.com/CAD97/reporting-examples/tree/rustdoc-syn-watt-proc_macro2-hang>

Running `cargo doc --no-deps` hangs on the locally defined crate. `cargo doc` hangs on syn.

Required bits to observe the hang:

- `syn` has the `full` feature enabled,
- `proc-macro2` is `[patch.crates-io]`d to `{ git = "https://github.com/dtolnay/watt" }`, and
- A type in the local crate mentions a `syn` type (not required for nonlocal hang). From my testing, "leaf" syn types do not trigger the hang; types that transitively contain `syn::Type` (and thus participate in syn's mutually recursive structure nature) do.

Due to the extent of syn's cyclic ast hierarchy, I wasn't able to reduce the repro case any further.

What makes this interesting is that rustdoc hangs _after_ checking/compiling syn, when documenting the local crate (when using `--no-deps`). Merely _containing_ the `syn` ast, even if it's not public, is enough to cause rustdoc to hang.

<details><summary>Reproduction</summary>

## Cargo.toml

```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "1.0.13", features = ["full"] }

[patch.crates-io]
proc-macro2 = { git = "https://github.com/dtolnay/watt" }
```

## lib.rs

```rust
struct S(syn::Type);
```
