### ISSUE TITLE
Reexports from other crate are listen in docs even when hidden by other types

### ISSUE THREAD

**Issue by DomantasJ** [rust-lang/rust#70390]
Given a two crate set up:

* Crate `a`:
    ```toml
    [package]
    name = "a"
    version = "0.1.0"
    edition = "2018"
    ```

    ```rust
    /// I am `a::Foo`
    pub struct Foo;
    ```

* Crate `b`:

    ```toml
    [package]
    name = "b"
    version = "0.1.0"
    edition = "2018"

    [dependencies]
    a = { path = "../a" }
    ```

    ```rust
    pub use a::*;

    /// I am `b::Foo`
    pub struct Foo;
    ```

Documentation for crate `b` lists two `Foo` types, with the `a::Foo` one being inaccessible because it is actually hidden by `b::Foo`:

![image](https://user-images.githubusercontent.com/41150975/77530118-8940d300-6e99-11ea-99f2-9c0d0f793e65.png)

If you change `a` to a module instead of a separate crate, then only `b::Foo` type is listed in docs.

```rust
mod a {
    /// I am `b::a::Foo`
    pub struct Foo;
}

pub use self::a::*;

/// I am `b::Foo`
pub struct Foo;
```

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-pc-windows-msvc
release: 1.42.0
LLVM version: 9.0
```

Real world example of this: [`diesel::r2d2`](https://docs.rs/diesel/1.4.4/diesel/r2d2/index.html) lists a struct `Error` which is defined by diesel, and an enum `Error` which is glob-reexported from `r2d2`.
