### ISSUE TITLE
failing to build individual tools via x.py

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#71307]
Running `./x.py build` results in all tools built, even though I asked for one, using the following `config.toml`:
```toml
[build]
compiler-docs = true
extended = true
tools = ["rustfmt"]
```

This issue has been assigned to @mati865 via [this comment](https://github.com/rust-lang/rust/issues/71307#issuecomment-616088232).
