### ISSUE TITLE
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17

### ISSUE THREAD

**Issue by OoLunar** [rust-lang/rust#72070]
I was attempting to use [rocket.rs](https://rocket.rs) as a file server. Using Rust Analysis from the [VSC Rust extension](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust), the code seems to be fine. When compiling on Rust Nightly, I get this lovely error:
```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17
```
Here's everything that _I think_ is required:
Backtrace: https://haste.natsumi.dev/acadolikuz.txt
```
lunar@J-Laptop-Ubuntu:~/Code/Github/File Server/v2$ rustc --version --verbose
rustc 1.45.0-nightly (bad3bf622 2020-05-09)
binary: rustc
commit-hash: bad3bf622bded50a97c0a54e29350eada2a3a169
commit-date: 2020-05-09
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```
Cargo.toml:
```toml
[package]
name = "file_server"
version = "0.1.0"
authors = ["Lunar <lunar@forsaken-borders.net>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
```
Source: https://haste.natsumi.dev/unuzeyigay.rs

If anything else is required, please let me know.
