### ISSUE TITLE
It's not possible to override the revision of a git repo using [patch]

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#72643]
Some of my dependencies depend on a git repo, but one of my dependencies doesn't compile with the latest version so I'm trying to temporarily switch to an older revision:

``` toml
# This dependency is in another crate
cgmath = { git = "https://github.com/rustgd/cgmath" }

# Attempt to override in main crate
[patch."https://github.com/rustgd/cgmath"]
cgmath = { git = "https://github.com/rustgd/cgmath", rev = "50a345b" }
```

Unfortunately this gives the following error:
```
error: failed to resolve patches for `https://github.com/rustgd/cgmath`

Caused by:
  patch for `cgmath` in `https://github.com/rustgd/cgmath` points to the same source, but patches must point to different sources
```

Is this a bug, or expected behavior? If it's not a bug, is there another way to achieve this, without having to clone the git repo?

This happens on both stable and nightly.
