### ISSUE TITLE
Unable to resolve item across crates

### ISSUE THREAD

**Issue by tones111** [rust-lang/rust#75576]
I have a crate that describes some common types (liba) and some others (libb) that are generated which declare instances of variables from the common crate.  I would like to write a test in the common crate but am unable to determine how to specify the path to the item from the generated crate.  The compiler complains of a type mismatch. I'm able to work around the problem in the case where I can destructure the value, but haven't found a workaround for the case where the item is an instance of an enum.

This minimal reproduction results in the following error when trying to `cargo test` in liba:
```
error[E0308]: mismatched types
 --> liba/src/lib.rs:8:26
  |
8 |         if libb::VAL1 != (crate::SomeType{x: 1}) {
  |                          ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `liba::SomeType`, found struct `SomeType`
```

liba/Cargo.toml:
```toml
[package]
name = "liba"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
libb = { path = "../libb" }
```

liba/src/lib.rs
```rust
#[derive(PartialEq)]
pub struct SomeType{pub x: u8}

#[cfg(test)]
mod tests {
    #[test]
    fn atest() {
        if libb::VAL1 != (crate::SomeType{x: 1}) {
            panic!();
        }
    }
}
```

libb/Cargo.toml:
```toml
[package]
name = "libb"
version = "0.1.0"
edition = "2018"

[dependencies]
liba = { path = "../liba" }
```

libb/src/lib.rs
```rust
pub const VAL1: liba::SomeType = liba::SomeType{x: 1};
```

The rust reference for [canonical paths](https://doc.rust-lang.org/reference/paths.html#canonical-paths) states
> The canonical path is only meaningful within a given crate. There is no global namespace across crates; an item's canonical path merely identifies it within the crate.

However, I would have expected the compiler to realize that crate::SomeType is equivalent to liba::SomeType in this case.

If I try to refer to it by name instead I get errors like:
```
8 |         if libb::VAL1 != (::liba::SomeType{x: 1}) {
  |                             ^^^^ could not find `liba` in `{{root}}`
```
```
8 |         if libb::VAL1 != (liba::SomeType{x: 1}) {
  |                           ^^^^ use of undeclared type or module `liba`
```
