### ISSUE TITLE
src/librustc_mir/borrow_check/type_check/free_region_relations.rs:316: failed to compute implied bounds 

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust#77018]
### Code

```Rust
# TODO, currently I'm not sure where it is.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
```

### Error output

```
error: internal compiler error: src/librustc_mir/borrow_check/type_check/free_region_relations.rs:316: failed to compute implied bounds [static generator@src/rsmq/receiver.rs:67:39: 94:2 msg:rsmq_async::RsmqMessage for<'r, 's, 't0, 't1, 't2> {rsmq_async::RsmqMessage, std::string::String, &'r str, &'s std::string::String, std::result::Result<model::elastic::RsmqMsg, serde_json::error::Error>, model::elastic::RsmqMsg, &'t0 model::elastic::OperationLog, &'t1 actix::address::Addr<elastic::client::EsClient<model::elastic::RsmqMsg>>, immutable::ES_EXECUTOR, elastic::client::EsCmd<model::elastic::RsmqMsg>, actix::address::message::Request<elastic::client::EsClient<model::elastic::RsmqMsg>, elastic::client::EsCmd<model::elastic::RsmqMsg>>, (), &'t2 model::elastic::CouponLog}]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1031
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  14: std::panicking::begin_panic
  15: rustc_errors::HandlerInner::bug
  16: rustc_errors::Handler::bug
  17: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  18: rustc::ty::context::tls::with_opt::{{closure}}
  19: rustc::ty::context::tls::with_opt
  20: rustc::util::bug::opt_span_bug_fmt
  21: rustc::util::bug::bug_fmt
  22: rustc_mir::borrow_check::type_check::free_region_relations::UniversalRegionRelationsBuilder::add_implied_bounds::{{closure}}
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  24: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: rustc_mir::borrow_check::type_check::free_region_relations::create
  27: rustc_mir::borrow_check::type_check::type_check
  28: rustc_mir::borrow_check::nll::compute_regions
  29: rustc_mir::borrow_check::do_mir_borrowck
  30: rustc::ty::context::GlobalCtxt::enter_local
  31: rustc_mir::borrow_check::mir_borrowck
  32: rustc::ty::query::__query_compute::mir_borrowck
  33: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  36: rustc_mir::borrow_check::type_check::TypeChecker::check_rvalue
  37: rustc_mir::borrow_check::type_check::TypeChecker::typeck_mir
  38: rustc_mir::borrow_check::type_check::type_check
  39: rustc_mir::borrow_check::nll::compute_regions
  40: rustc_mir::borrow_check::do_mir_borrowck
  41: rustc::ty::context::GlobalCtxt::enter_local
  42: rustc_mir::borrow_check::mir_borrowck
  43: rustc::ty::query::__query_compute::mir_borrowck
  44: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  45: rustc::dep_graph::graph::DepGraph::with_task_impl
  46: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  47: rustc_typeck::collect::type_of::type_of
  48: rustc::ty::query::__query_compute::type_of
  49: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::type_of>::compute
  50: rustc::dep_graph::graph::DepGraph::with_task_impl
  51: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  52: rustc_infer::traits::select::SelectionContext::constituent_types_for_ty
  53: rustc_infer::traits::select::SelectionContext::confirm_candidate
  54: rustc_infer::infer::InferCtxt::probe
  55: rustc_infer::traits::select::SelectionContext::evaluate_stack
  56: rustc::dep_graph::graph::DepGraph::with_anon_task
  57: rustc_infer::traits::select::SelectionContext::evaluate_predicate_recursively
  58: rustc_infer::infer::InferCtxt::probe
  59: rustc_infer::traits::select::SelectionContext::evaluate_root_obligation
  60: rustc::ty::context::GlobalCtxt::enter_local
  61: rustc_traits::evaluate_obligation::evaluate_obligation
  62: rustc::ty::query::__query_compute::evaluate_obligation
  63: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::evaluate_obligation>::compute
  64: rustc::dep_graph::graph::DepGraph::with_task_impl
  65: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  66: rustc_infer::traits::query::evaluate_obligation::<impl rustc_infer::infer::InferCtxt>::evaluate_obligation
  67: rustc_infer::traits::query::evaluate_obligation::<impl rustc_infer::infer::InferCtxt>::predicate_must_hold_considering_regions
  68: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  69: <rustc_infer::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  70: rustc_typeck::check::FnCtxt::check_argument_types
  71: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
  72: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  73: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  74: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  75: rustc_typeck::check::FnCtxt::check_stmt
  76: rustc_typeck::check::FnCtxt::check_block_with_expected
  77: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  78: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  79: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  80: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  81: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  82: rustc_typeck::check::FnCtxt::check_block_with_expected
  83: rustc_typeck::check::FnCtxt::check_block_no_value
  84: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  85: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  86: rustc_typeck::check::FnCtxt::check_block_with_expected
  87: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  88: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  89: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  90: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  91: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  92: rustc_typeck::check::FnCtxt::check_block_with_expected
  93: rustc_typeck::check::FnCtxt::check_block_no_value
  94: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  95: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  96: rustc_typeck::check::FnCtxt::check_block_with_expected
  97: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  98: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  99: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
 100: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
 101: rustc_typeck::check::FnCtxt::check_block_with_expected
 102: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
 103: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
 104: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
 105: rustc_typeck::check::check_fn
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0 (4fb7144ed 2020-04-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `rsmq::receiver::handle_msg::{{closure}}#0`
#1 [mir_borrowck] borrow-checking `rsmq::receiver::handle_msg`
#2 [type_of] processing `rsmq::receiver::handle_msg::{{opaque}}#0`
#3 [evaluate_obligation] evaluating trait selection obligation `impl core::future::future::Future: std::marker::Send`
#4 [typeck_tables_of] type-checking `rsmq::receiver::start`
#5 [typeck_tables_of] type-checking `rsmq::receiver::start::{{closure}}#0`
#6 [type_of] processing `rsmq::receiver::start::{{closure}}#0`
#7 [collect_mod_item_types] collecting item types in module `rsmq::receiver`
#8 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `sbl_manager`.

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by GopherJ** [comment]
This error seems happened in: https://github.com/GopherJ/rsmq-async-rs

**Comment by jonas-schievink** [comment]
Rust 1.43.0 is old, please retry on the newest nightly.

**Comment by GopherJ** [comment]
@jonas-schievink I'm trying, I saw the error message mentioned `src/rsmq/receiver`. I can show this part of code:

```
use crate::{
    elastic::{EsCmd, EsResult},
    immutable::{
        ES_EXECUTOR, REDIS_DB, REDIS_HOST, REDIS_PORT, RSMQ_EXECUTOR,
        SHARED_MESSAGE_QUEUE,
    },
    model::elastic::RsmqMsg,
    rsmq::RsmqCmd,
};

use backoff::{backoff::Backoff, ExponentialBackoff};
use log::error;
use rsmq_async::{Rsmq, RsmqMessage, RsmqOptions};
use tokio::{task::spawn, time::delay_for};

use std::time::Duration;

pub async fn start() {
    let mut backoff = ExponentialBackoff::default();
    backoff.max_elapsed_time = None;

    let opts = RsmqOptions {
        host: REDIS_HOST.to_owned(),
        port: REDIS_PORT.to_owned(),
        db: REDIS_DB.to_owned(),
        ..Default::default()
    };

    'outer: loop {
        match Rsmq::new(opts.clone()).await {
            Ok(mut rsmq) => {
                backoff.reset();

                loop {
                    match rsmq
                        .receive_message(
                            SHARED_MESSAGE_QUEUE.as_str(),
                            Some(90),
                        )
                        .await
                    {
                        Ok(Some(msg)) => {
                            spawn(handle_msg(msg));
                        }
                        Err(err) => {
                            error!("failed to receive message: {}", err);
                            break 'outer;
                        }
                        Ok(None) => {
                            delay_for(Duration::from_secs(3)).await;
                        }
                    }
                }
            }
            Err(err) => {
                error!("Cannot conect to redis server: {:?}", err);
                if let Some(timeout) = backoff.next_backoff() {
                    delay_for(timeout).await
                } else {
                    backoff.reset()
                }
            }
        }
    }
}

async fn handle_msg(msg: RsmqMessage) {
    let msg_id = msg.id.to_owned();
    match serde_json::from_str::<RsmqMsg>(&msg.message) {
        Ok(rsmq_msg) => {
            let res = match rsmq_msg {
                RsmqMsg::OperationLog(ref _operation_log) => {
                    ES_EXECUTOR
                        .send(EsCmd::Index("logs".to_owned(), rsmq_msg))
                        .await
                }
                RsmqMsg::CouponLog(ref _coupon_log) => {
                    ES_EXECUTOR
                        .send(EsCmd::Index("coupons".to_owned(), rsmq_msg))
                        .await
                }
            };

            match res {
                Ok(Ok(EsResult::Index)) => {
                    RSMQ_EXECUTOR.do_send(RsmqCmd::DeleteMessage(msg_id));
                }
                Ok(Err(err)) => error!("failed to index message: {}", err),
                _ => {}
            }
        }
        Err(err) => error!("failed to deserialize rsmq message: {}", err),
    }
}
```

**Comment by GopherJ** [comment]
@jonas-schievink just verified it's the same error, I cannot compile my project

**Comment by GopherJ** [comment]
The `Cargo.toml` in case it helps:

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "2.0.0", default-features = false, features = ["rustls", "compress"] }
env_logger = "0.7.1"
log = "0.4.8"
thiserror = "1.0.15"
actix-web-actors = "2.0.0"
actix-rt = "1.1.0"
clap = { version = "2.33.0", features = ["suggestions", "color"] }
lazy_static = "1.4.0"
actix = "0.9.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
futures = { version = "0.3.4" }
backoff = "0.1.6"
rust-embed = { version = "5.6.0", features = ["compression"] }
mime_guess = "2.0.3"
tokio = { version = "0.2.13", features = ["net", "fs", "sync", "io-util", "rt-core", "blocking", "rt-threaded", "time"] }
actix-cors = "0.2.0"
uuid = { version = "0.8.1", features = ["v4"] }
elasticsearch = { version = "7.7.0-alpha.1", default-features = false, features = ["rustls-tls"] }
url = "2.1.1"
redis = "0.17.0"
reqwest = { version = "0.10.4", features = ["json", "stream", "rustls-tls", "gzip"] }
toml = "0.5.6"
diesel = { version = "1.4.2", features = ["r2d2", "postgres", "chrono", "uuid"] }
actix-web-httpauth = { version = "0.4.0", path = "third-party/actix-web-httpauth" }
r2d2 = "0.8.8"
derive_builder = "0.9.0"
chrono = { version = "0.4.15", features = ["serde"] }
tonic = {  git = "https://github.com/GopherJ/tonic", branch="consume-connect", features = ["transport"] }
prost = "0.6.1"
prost-types = "0.6.1"
prost-derive = "0.6.1"
semver = "0.9.0"
regex = "1.3.9"
rsmq_async = { git = "https://github.com/GopherJ/rsmq-async-rs", branch = "master" }
sendgrid = { git = "https://github.com/GopherJ/sendgrid-rs", branch = "master", features = ["async"] }

# make diesel being able to be compiled through musl
openssl = "0.10.29"
openssl-probe = "0.1.2"

[build-dependencies]
tonic-build = { version = "^0.3.0", features = ["prost"] }
chrono = "0.4.15"
```
