### ISSUE TITLE
proc-macro receives warnings only when used within `macro_rules!` macros

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#77973]
A proc-macro that generates code with the partial same span as the input, receive warnings in the generated code only when used within `macro_rules!` macros. (does not receive warnings if used outside `macro_rules!` macros.)

*This originally reported in https://github.com/taiki-e/pin-project/pull/298* ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fb33b572fc967f70710edb5026083266)).

### Repro:

`Cargo.toml`:

```toml
[package]
name = "repro"
version = "0.0.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
```

`src/lib.rs`:

```rust
extern crate proc_macro;

use proc_macro::TokenStream;
use proc_macro2::{Ident, Span};
use quote::quote;

#[proc_macro_attribute]
pub fn repro(_arg: TokenStream, input: TokenStream) -> TokenStream {
    let item: syn::ItemStruct = syn::parse_macro_input!(input);

    let name = format!("{}2", &item.ident);
    let name = Ident::new(&name, Span::call_site());
    let vis = &item.vis;

    TokenStream::from(quote! {
        #item
        // can be avoid by adding `#[allow(missing_debug_implementations)]`
        // or change `vis` to call-site span
        #vis struct #name {
            _f: ()
        }
    })
}
```

`tests/test.rs`:

```rust
#![warn(missing_debug_implementations)]

#[repro::repro] // <- no warning
#[derive(Debug)]
pub struct A {
    _f: (),
}

macro_rules! mac {
    () => {
        #[repro::repro] //~WARN type does not implement `Debug`
        #[derive(Debug)]
        pub struct B {
            _f: (),
        }
    };
}

mac!();
```

This example uses `missing_debug_implementations`, but the same problem occurred with `unreachable_pub`, `variant_size_differences`, `clippy::missing_const_for_fn` etc., so it doesn't seem to be specific to some lint.

### Meta

It can be reproduced at least in 1.31, stable (1.47), beta (1.48), nightly-2020-10-15.

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (e160e5cb8 2020-10-14)
binary: rustc
commit-hash: e160e5cb80652bc2afe74cb3affbe35b74243ea9
commit-date: 2020-10-14
host: x86_64-apple-darwin
release: 1.49.0-nightly
LLVM version: 11.0
```
