### ISSUE TITLE
unused_crate_dependencies false positives when dependency used only in doctests

### ISSUE THREAD

**Issue by Hawk777** [rust-lang/rust#78346]
If a dependency is only used in a doctest, it triggers an `unused_crate_dependencies` false positive.

I tried this code:

`main.rs`:
```rust
#![warn(unused_crate_dependencies)]

///! # Example
///! ```
///! use gcd::Gcd;
///! assert_eq!(6u32.gcd(8u32), 2u32);
///! ```

fn main() {
}
```

`cargo.Toml`:
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dev-dependencies.gcd]
version = "^2.0"
```

I expected to see this happen: No warnings.

Instead, this happened: `cargo test` generates an `unused_crate_dependencies` warning for the `gcd` crate.

### Meta
`rustc --version --verbose`:
```
rustc 1.46.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```
