### ISSUE TITLE
SEGFAULT on 'nightly' toolchain cross-compiling for i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by semiviral** [rust-lang/rust#79657]
### Code
```toml
# cargo.toml

[package]
name = "kernel"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "*", features = ["spin_no_std"] }
volatile = "0.2.6"
spin = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
path = "src/kernel.rs"
crate-type = ["staticlib"]
```

```toml
# config.toml

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686-unknown-linux-gnu"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-args=-m32"
    ]
```

```json
(this is the build target, i.e. "x86-unknown-none.json")

{
    "llvm-target": "i686-unknown-linux-gnu",
    "data-layout": "e-m:e-n8:16:32-p:32:32",
    "arch": "x86",
    "target-endian": "little",
    "target-pointer-width": "32",
    "target-c-int-width": "32",
    "os": "none",
    "executables": true,
    "linker": "ld.lld",
    "linker-flavor": "rust-lld",
    "panic-strategy": "abort",
    "disable-redzone": true,
    "features": "-mmx,-sse,+soft-float"
}
```

***remark:** anything else project-wise you might think relevant can be found [in the project repo](https://github.com/avirule/gsai_os) (prefer browsing the repo at the initial commit for the exact conditions that led to the issue)*

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

### Error output

```
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2018 /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C metadata=6fd114a6ec2d4f77 -C extra-filename=-6fd114a6ec2d4f77 --out-dir /home/whiterabbit/git/gsai_os/target/i686-unknown-linux-gnu/release/deps --target i686-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/whiterabbit/git/gsai_os/target/i686-unknown-linux-gnu/release/deps -L dependency=/home/whiterabbit/git/gsai_os/target/release/deps --cap-lints allow -C relocation-model=static -C link-args=-m32` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
(gdb) bt
#0  0x00007fffefd4bc5e in (anonymous namespace)::MachineCSE::runOnMachineFunction(llvm::MachineFunction&) ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-11-rust-1.50.0-nightly.so
#1  0x00007fffefd6d78e in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-11-rust-1.50.0-nightly.so
#2  0x00007fffefb47fd2 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-11-rust-1.50.0-nightly.so
#3  0x00007fffefb4e9e3 in llvm::FPPassManager::runOnModule(llvm::Module&) ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-11-rust-1.50.0-nightly.so
#4  0x00007fffefb48a2a in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/libLLVM-11-rust-1.50.0-nightly.so
#5  0x00007ffff3f08d50 in LLVMRustWriteOutputFile ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#6  0x00007ffff3e4777c in rustc_codegen_llvm::back::write::write_output_file ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#7  0x00007ffff3e4bf9e in rustc_codegen_llvm::back::write::codegen ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#8  0x00007ffff3e2de2b in rustc_codegen_ssa::back::write::finish_intra_module_work ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#9  0x00007ffff3e279d6 in rustc_codegen_ssa::back::write::execute_work_item ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#10 0x00007ffff3d0a91f in std::sys_common::backtrace::__rust_begin_short_backtrace ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#11 0x00007ffff3d104ad in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
   from /home/whiterabbit/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-4f0cc9f50e53f0ba.so
#12 0x00007ffff31a165a in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once ()
    at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/alloc/src/boxed.rs:1318
#13 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/alloc/src/boxed.rs:1318
#14 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#15 0x00007ffff2edd6db in start_thread (arg=0x7fff9e17f700) at pthread_create.c:463
#16 0x00007ffff27fa71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

</p>
</details>
