### ISSUE TITLE
`cargo test --features dep/feat` does not imply `--features dep` in beta

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#83131]
In rustc 1.50.0, `cargo --features dep/feat` also seems to imply `--features dep`, but this does not seem to be the case in 1.51.0-beta.6.

For example, for two library crates `foo` and `bar`.

foo/Cargo.toml:
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[features]
foof = []
```

bar/Cargo.toml:
```toml
[package]
name = "bar"
version = "0.1.0"
edition = "2018"

[dependencies.foo]
path = "../foo"
optional = true
```

This works with stable rustc 1.50.0 (cb75ad5db 2021-02-10):
```sh
$ cargo +stable test --features foo/foof -p foo
```

This gives an error with beta rustc 1.51.0-beta.6 (6a1835ad7 2021-03-12):
```sh
$ cargo +beta test --features foo/foof -p foo
error: package ID specification `foo` did not match any packages
```

I don't know if this used to work unintentionally up to 1.50.0 and the "glitch got fixed" in the beta.

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged
