### ISSUE TITLE
Upgrade to LLVM 12 caused AArch64 bare metal program run incorrectly

### ISSUE THREAD

**Issue by songzhi** [rust-lang/rust#83335]
Here's the [project](https://github.com/lowenware/leos-kernel) (as an example).
It run correctly when the following toolchain is used: 
```toml
[toolchain]
channel = "nightly-2021-03-04"
targets = ["aarch64-unknown-none-softfloat"]
```
And incorrectly when the following toolchain is used:
```toml
[toolchain]
channel = "nightly-2021-03-05"
targets = ["aarch64-unknown-none-softfloat"]
```
So I think it related to #81451 the upgrade to LLVM 12.
I don't know the exact reason, but back to `nightly-2021-03-04` works for me now.
