### ISSUE TITLE
-Z profile broken since the upgrade to LLVM 11

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#83552]
The same errors as #50203 (cannot merge previous GCDA file: corrupt arc tag) are happening again, starting with nightly-2020-08-24 (5180f3da5), which is the first nightly after #73526.

I'm using the flags `-Zprofile -Ccodegen-units=1 -Cinline-threshold=0`, and setting `CARGO_INCREMENTAL=0` in the environment.

**Comment by glandium** [comment]
This looks like a LLVM issue purely. If I upgrade the C compiler to LLVM 11 too, then it works (this was on a crate with ffi code). I guess this is not something rust can do anything about.

**Comment by wllenyj** [comment]
The same problem reappeared in 1.60.0-nightly (09cb29c64 2022-02-15)
```
    ubuntu: info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'
    ubuntu:   nightly-x86_64-unknown-linux-gnu installed - rustc 1.60.0-nightly (09cb29c64 2022-02-15)
    ubuntu: 
    ubuntu: 
    ubuntu: Rust is installed now. Great!
```
See https://github.com/wllenyj/dragonball-sandbox/runs/5212083346 for details.
