### ISSUE TITLE
"edition" Field In Cargo.toml Could Cause Potential Confusion

### ISSUE THREAD

**Issue by XtremeDevX** [rust-lang/rust#84388]
To those new to rust or to those who have not seen `https://doc.rust-lang.org/cargo/reference/manifest.html#the-edition-field`, the `edition` field is confusing.
 
 ```toml
 [package]
name = "volt"
version = "0.1.0"
authors = ["XtremeDevX <xtremedevx@gmail.com>"]
description = "A fast, memory-safe package manager for the web."
edition = "2018"
 ```

Take the above `[package]` section. According to the [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-manifest-format), you can add all sorts of details about the project itself like a description etc. 

However, when newer users (and others) see `2018` for the `edition` field, they are confused by what the `version` field means. 

Is `version` the rust version that the software or crate runs on or is the `edition` the edition the crate or software is currently in or is `edition` the year during which the software or crate was published?

### Proposed Solution

This problem can be tackled easily. Here's a list of tags that would be less confusing to people:
```
rust-v
rust-version
rustv
```

However a restructure of the Cargo.toml would be better:
```toml
[info] # info stores details about the crate or software itself
name = "volt"
version = "0.1.0"
authors = ["XtremeDevX <xtremedevx@gmail.com>"]
description = "A fast, memory-safe package manager for the web."

[config] # or [dev-env] or [dev]
rust-edition = "2018" # or rust-version = "2018"
```
