### ISSUE TITLE
rustdoc: align .stab to the right on desktop

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#86767]
The informative tags/labels/stabs have been moved to the left column to improve the mobile experience.
Now the table feels a bit crammed.

* One possibility is to increase the gaps between the symbol and the tags.
* Another is to align the tags to the right on the desktop.

## Current nightly 2021-06-30

![image](https://user-images.githubusercontent.com/739070/124043946-bc0e3b00-d9fb-11eb-8d07-7aa542ce51b1.png)

## First draft for implementation

One possibility is something like this, but these rules result in stretched out:

![image](https://user-images.githubusercontent.com/739070/124043846-794c6300-d9fb-11eb-803b-e1542aa0aac7.png)

```css
.item-left {
    grid-column: 1;
    /* added */
    display: flex;
    justify-content: space-between;
    flex-flow: row wrap;
    width: 100%;
}
```

Based on: #86725 #86594
CC: @GuillaumeGomez
