### ISSUE TITLE
Renaming of feature can cause unexpected behavior

### ISSUE THREAD

**Issue by ralpha** [rust-lang/rust#87630]
Renaming of a feature can cause behavior changes if name is also used for an optional dependency.
This will not trigger any warnings or errors from the compiler.

I'll set up 2 parts here, before crate change and after crate change.

## Before create change
Code example:
My crate `my_crate/Cargo.toml` file has this section:
```toml
[dependencies]
some_crate = { version = "0.1.0", features = ["old_feature_name"] }
```

The other crate `some_crate/Cargo.toml`:
```toml
[features]
old_feature_name = ["old_feature_name"]

[dependencies]
old_feature_name = { version = "0.2.0", optional = true }
```
And `some_crate/src/lib.rs`:
```rust
fn enable_important_feature() {
    println!("Important feature is enabled");
}

fn main() {
    #[cfg(feature = "old_feature_name")]
    enable_important_feature();
}
```
This will print `Important feature is enabled` as expected, no problems yet.

## After create change
Now the feature is renamed from `old_feature_name` to `new_feature_name`.

I did not know about the feature change so my file did not change:
(Note: I might had to check this, but lets say this change was not documented and/or was not manually checked when updating versions. I don't think this is an unreasonable assumption.)
`my_crate/Cargo.toml`:
```toml
[dependencies]
some_crate = { version = "0.2.0", features = ["old_feature_name"] }
```

`some_crate/Cargo.toml`:
```toml
[features]
new_feature_name = ["old_feature_name"]

[dependencies]
old_feature_name = { version = "0.2.0", optional = true }
```
`some_crate/src/lib.rs`:
```rust
fn enable_important_feature() {
    println!("Important feature is enabled");
}

fn main() {
    #[cfg(feature = "new_feature_name")]
    enable_important_feature();
}
```

This will not trigger any compiler warnings/errors because although feature does not exists, an optional create with that name does exists.
This, as you might expect, will not print anything. (As this is currently intended this way by the compiler)

## Solution
This is currently the only "reasonable" solution I can think. Because other changes might have much bigger complications.

Change the crate to also redirect the old feature to the new feature:
`some_crate/Cargo.toml`:
```toml
[features]
new_feature_name = ["old_feature_name"]
# Make change backwards compatible with old feature
# The optional dependency also needs to be enabled
# This depends on: https://github.com/rust-lang/rfcs/pull/3143 (should be merged soon in stable)
# For old rust version see: https://blog.turbo.fish/cargo-features/
old_feature_name = ["new_feature_name", "dep:old_feature_name"]

[dependencies]
old_feature_name = { version = "0.2.0", optional = true }
```

I don't think there are changes in the compiler itself that can reasonably fix this, but this at least record the problem and a way to solve it.

I'll close this issue so it can be used to track future people that have this problem.
