### ISSUE TITLE
--remap-path-prefix has no effect

### ISSUE THREAD

**Issue by Sebi2020** [rust-lang/rust#87805]
I tried this code: Not applicable

I expected to see this happen: *--remap-path-prefix should rewrite paths to the new prefix, but fails.*

Instead, this happened: *Paths are still persistent in the binary or rlib*

### Meta

Steps to reproduce:
1. Build a lib or program on windows with rustc 1.54.0 and msvc with --remap-path-prefix in .cargo/config.toml (project directory)
2. Path prefix is not applied. Old paths still present in binary and/or rlib.

I tried C:\\path\\to\\project and C:/path/to/project in the from path. Both failed to work.

`rustc --version --verbose`:
```
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-pc-windows-msvc
release: 1.54.0
LLVM version: 12.0.1
```

Backtrace: Not applicable

**Comment by SkiFire13** [comment]
I can't seem to fully reproduce this. 

My `C:\path\to\project\.cargo\config.toml`:
```toml
[build]
rustflags = ["--remap-path-prefix", "C:\\path\\to\\project=nothing_to_see_here"]
```
I've also tried with the following and the results are the same:
```toml
[build]
rustflags = ["--remap-path-prefix", "G:/WorkSpace/rust-playground=nothing_to_see_here"]
```

Building a lib results in a `.rlib` file that doesn't contain `C:\path\to\project`. 

Building a binary however results in a `.exe` file that contains `C:\path\to\project\target\release\deps\crate_name.pdb`. In general however paths seem to be correctly mapped, for example if I set `RUST_BACKTRACE=1` and then panic in a debug build the backtrace will show the path starting with `nothing_to_see_here`.
