### ISSUE TITLE
Compiling a Rocket application on the 2015 edition doesn't emit errors

### ISSUE THREAD

**Issue by ferrohd** [rust-lang/rust#89699]
When trying to compile any Rocket application in the 2015 edition the compiler says an error occured without showing any actual error:

```
$ RUST_BACKTRACE=1 cargo build
   Compiling repro v0.1.0
error: could not compile `repro`
$
```

Switching to the 2018 edition fixes the problem, by either showing errors or properly compiling the application. Minimal reproduction:

```rust
// src/main.rs

#[rocket::launch]
fn foo() -> _ {
    rocket::build()
}
```

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.1.0"
edition = "2015"

[dependencies]
rocket = "0.5.0-rc.1"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: x86_64-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```
