### ISSUE TITLE
Unwrap of None while compiling dependencies (stm32f1 v0.9.0)

### ISSUE THREAD

**Issue by mjdr** [rust-lang/rust#89969]
## Cargo ouput:
```
   Compiling typenum v1.14.0
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v1.0.30
   Compiling version_check v0.9.3
   Compiling cortex-m v0.7.3
   Compiling semver v1.0.4
   Compiling unicode-xid v0.2.2
   Compiling nb v1.0.0
   Compiling syn v1.0.80
   Compiling void v1.0.2
   Compiling vcell v0.1.3
   Compiling stable_deref_trait v1.2.0
   Compiling cortex-m-rt v0.6.15
   Compiling bitfield v0.13.2
   Compiling cortex-m v0.6.7
   Compiling stm32f1 v0.9.0
   Compiling r0 v0.2.2
   Compiling cortex-m-semihosting v0.3.7
   Compiling panic-halt v0.2.0
   Compiling semver v0.9.0
   Compiling generic-array v0.14.4
   Compiling nb v0.1.3
   Compiling volatile-register v0.2.1
   Compiling rustc_version v0.2.3
   Compiling embedded-hal v0.2.6
   Compiling bare-metal v0.2.5
   Compiling generic-array v0.12.4
   Compiling generic-array v0.13.3
   Compiling quote v1.0.10
   Compiling rustc_version v0.4.0
   Compiling cast v0.2.7
   Compiling as-slice v0.1.5
   Compiling aligned v0.3.5
   Compiling cortex-m-rt-macros v0.6.15
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_typeck/src/coherence/inherent_impls_overlap.rs:242:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (d7c97a02d 2021-10-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [crate_inherent_impls_overlap_check] check for overlap between inherent impls defined in this crate
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `stm32f1`
```

## Cargo.toml
```toml
[package]
name = "stm32f103c8t6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "*"
cortex-m-rt = "*"
cortex-m-semihosting = "*"
panic-halt = "*"
nb = "0.1.2"
embedded-hal = "0.2.3"
stm32f1xx-hal = {version="0.5.2", features=["stm32f100", "rt"]}


[profile.release]
codegen-units = 1
debug = false
lto = true
```
## .cargo/config
```toml
[target.thumbv7m-none-eabi]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']

rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "thumbv7m-none-eabi"
```

## src/main.rs
```rust
fn main() {
    println!("Hello, world!");
}
```

# Workaround
Replace `edition = "2021"` with `edition = "2018"` in Cargo.toml
