### ISSUE TITLE
`std::env::vars` and `std::env::args` should silently ignore non-UTF8 values

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/rust#91226]
[`std::env::vars`](https://doc.rust-lang.org/std/env/fn.vars.html) and [`std::env::args`](https://doc.rust-lang.org/std/env/fn.args.html) both panic when they encounter non-UTF8 values.

This is harmful for several reason:

1. It means binaries can fail simply because someone else set an env var that ended up in the user's environment (e.g, [cargo](https://github.com/rust-lang/cargo/blob/58a961314437258065e23cb6316dfc121d96fb71/crates/credential/cargo-credential/src/lib.rs#L52))
1. Disallowing through linters like `clippy` is not enough since clippy doesn't look at dependencies that are non-local. If one of them calls `std::env::vars`, it is possible to crash the end product without a lot of efforts.
1. Environment variables and arguments are inherently system-specific, panicking at the slightest mistake or mistype seems like a bad idea when it could happen for any number of reasons.
1. In managed computers, e.g. a Windows for an employee, users may not have the right to modify some env vars or any of them. If one is causing crashes because of this, it's not good.

Instead of panicking (though it is better than unknown behavior), such cases should simply be ignored instead.

Example to see what happens:

<details><summary>Code</summary>

```rust
// src/main.rs

use std::{ffi::OsStr, os::unix::prelude::OsStrExt, process::Command};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let s = &"\u{2764}".as_bytes()[..1];
    let s = OsStr::from_bytes(s);

    Command::new("cargo")
        .arg("login")
        .arg(s)
        .spawn()?;

    Ok(())
}
```

```toml
# Cargo.toml

[package]
name = "reproducer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "welp, crashed the thing"
documentation = "https://google.com"
homepage = "https://google.com"
repository = "https://google.com"
```

</details>

Result:

```
thread 'main' panicked at 'unexpected invalid UTF-8 code point', /cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/args/arg_matches.rs:118:40                                                          
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@rustbot label T-libs T-libs-api
