### ISSUE TITLE
`python x.py check` always rebuilds `rustc_llvm` on Windows

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/rust#92369]
I have forked the rust repository, and I made a change. When running `python x.py check`, `rustc_llvm` always rebuilds.

**Comment by BGR360** [comment]
Can you please show your `config.toml`? And also the output of `x.py check`?

**Comment by Milo123459** [comment]
This is `config.toml`:
```toml
# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2
```
The output of x.py check is what you would expect, except for rustc_llvm(build) starts at 306 and has to go up to 317 in modules.
