### ISSUE TITLE
Unhelpful error when `Cargo.toml` is missing `edition` key.

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#92422]
Given the following code: 

```toml
# Cargo.toml
[package]
name = "no-edition-diagnostics"
version = "0.1.0"
# note the lack of edition = ""

[dependencies]
anyhow = "1"
```
```rust
// src/lib.rs
use anyhow::*;
```

The current output is:

```
error[E0432]: unresolved import `anyhow`
 --> src/lib.rs:1:5
  |
1 | use anyhow::*;
  |     ^^^^^^ maybe a missing crate `anyhow`?
```

Ideally the output should look like:

error[E0432]: unresolved import `anyhow`
 --> src/lib.rs:1:5
  |
1 | use anyhow::*;
  |     ^^^^^^ maybe a missing crate `anyhow`?
               hint: try adding an `extern crate` or move to a newer Rust edition
```

Since the solution for this case is _generally_ going to be one of those two.
