### ISSUE TITLE
[Consult] How to configure different crate-type on platforms?

### ISSUE THREAD

**Issue by niuhuan** [rust-lang/rust#94610]
I want use staticlib on macos, and  cdylib on android.

dependencies is ok, but  crate-type not work

```toml
[target.'cfg(target_os="macos")'.dependencies]
tokio = "0"
[target.'cfg(target_os="android")'.dependencies]
jni = "0"
```

```toml
[target.'cfg(target_os="macos")'.lib]
crate-type = ["staticlib"]

[target.'cfg(target_os="android")'.lib]
crate-type = ["cdylib"]
```

![13333](https://user-images.githubusercontent.com/20847533/156798215-8ee4c8d0-e341-4bea-b406-ec6bfc6ccd19.png)
