### ISSUE TITLE
Doc tests cannot be run on wasm32-unknown-unknown target using `doctest-xcompile` feature.

### ISSUE THREAD

**Issue by hamza1311** [rust-lang/rust#96532]
Doc tests cannot be run on wasm32-unknown-unknown target using `doctest-xcompile` feature.

Rustdoc tries to create a temporary directory on a target where there is no file system available and fails

## Steps to re-produce
1. Create a cargo project with the following structure:

<details>

<summary>
<code>src/lib.rs</code>
</summary>

```rust
/// ```rust
/// fn greet(name: &str) {
///     let window = web_sys::window().unwrap();
///     window.alert_with_message(&format!("Hello, {}!", name));
/// }
/// ```
pub fn do_nothing() {
}
```

</details>

<details>
<summary>
<code>Cargo.toml</code>
</summary>

```toml
[package]
name = "doctest-xcompile-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window"] }
```

</details>

<details>
<summary>
<code>.cargo/config</code>
</summary>

```toml
[target.'cfg(target_arch = "wasm32")']
runner = 'wasm-bindgen-test-runner'

[unstable]
doctest-xcompile = true
```

</details>

2. Ensure wasm-bindgen test runner is properly set-up to be used without wasm-pack. See [documentation](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#appendix-using-wasm-bindgen-test-without-wasm-pack).
3. Run `cargo +nightly test --doc --target wasm32-unknown-unknown`

## Expected behavior

Test runs successfully and passes.

## Actual behavior

```sh
$ cargo +nightly test --doc --target wasm32-unknown-unknown
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
   Doc-tests doctest-xcompile-bug

running 1 test
test src/lib.rs - do_nothing (line 1) ... FAILED

failures:

---- src/lib.rs - do_nothing (line 1) stdout ----
Test executable failed (exit status: 1).

stdout:
                                                  
stderr:
Error: creating temporary directory

Caused by:
    Permission denied (os error 13)



failures:
    src/lib.rs - do_nothing (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s

error: test failed, to rerun pass '--doc'
```

### Meta

```
$ rustc +nightly --version --verbose
rustc 1.62.0-nightly (69a5d2481 2022-04-27)
binary: rustc
commit-hash: 69a5d2481e856a5a18885390b8cf6950b9ff8dd3
commit-date: 2022-04-27
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```
