### ISSUE TITLE
Rustdoc shows broken anonymous lifetimes on re-exported signatures

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#98697]
```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
foo = { path = "foo" }
```

```rust
// src/lib.rs

pub use foo::repro;
```

```toml
# foo/Cargo.toml

[package]
name = "foo"
version = "0.0.0"
edition = "2021"
publish = false
```

```rust
// foo/src/lib.rs

pub fn repro<F>()
where
    F: Fn(&str),
{
    unimplemented!()
}
```

The correct behavior is for both crates' docs to render `repro` as:

<img src="https://user-images.githubusercontent.com/1940490/176577639-bd3508ac-5d84-463f-8987-c57af472dbc0.png" height="100">

However, recent versions of nightly rustdoc render `foo::repro` as the above, while rendering `repro::repro` incorrectly as:

<img src="https://user-images.githubusercontent.com/1940490/176577739-562a6382-9592-4e98-8080-912fe95be5a7.png" height="100">

I believe this is a bug because that is not valid syntax in Rust.

```console
error[E0637]: `'_` cannot be used here
 --> src/lib.rs:3:12
  |
3 |     F: for<'_> Fn(&str),
  |            ^^ `'_` is a reserved lifetime name
```
